
[rclick jump=true storage="album.ks" target=*album_loop0 enabled=true]
[eval exp="sf.showpagebreak = 0"]

*001|
[rclick jump=true target="*album_menu" storage="album.ks" enabled=true]
[eval exp="sf.showpagebreak = 0"]
[er]
[layopt layer=massage0 page=back visible=false]
;”wŒiƒŒƒCƒ„‚Ì•\E— ‰æ–Ê‚É‰æ‘œ‚ğ“Ç‚İ‚Ş
[image storage="CG1_1" layer=base page=fore]
[p]
[image storage="CG1_2" layer=base page=fore]
[p]
[image storage="CG1_3" layer=base page=fore]
[p]
[wait time=300 mode="normal" canskip=false]
[jump storage="album.ks" target=*album_loop0]

*002|
[rclick jump=true target="*album_menu" storage="album.ks" enabled=true]
[eval exp="sf.showpagebreak = 0"]
[er]
[layopt layer=massage0 page=back visible=false]
;”wŒiƒŒƒCƒ„‚Ì•\E— ‰æ–Ê‚É‰æ‘œ‚ğ“Ç‚İ‚Ş
[image storage="CG2_1" layer=base page=fore]
[p]
[image storage="CG2_2" layer=base page=fore]
[p]
[image storage="CG2_3" layer=base page=fore]
[p]
[wait time=300 mode="normal" canskip=false]
[jump storage="album.ks" target=*album_loop0]

*003|
[rclick jump=true target="*album_menu" storage="album.ks" enabled=true]
[eval exp="sf.showpagebreak = 0"]
[er]
[layopt layer=massage0 page=back visible=false]
;”wŒiƒŒƒCƒ„‚Ì•\E— ‰æ–Ê‚É‰æ‘œ‚ğ“Ç‚İ‚Ş
[image storage="CG3_1" layer=base page=fore]
[p]
[image storage="CG3_2" layer=base page=fore]
[p]
[image storage="CG3_3" layer=base page=fore]
[p]
[image storage="CG3_4" layer=base page=fore]
[p]
[wait time=300 mode="normal" canskip=false]
[jump storage="album.ks" target=*album_loop0]

*004|
[rclick jump=true target="*album_menu" storage="album.ks" enabled=true]
[eval exp="sf.showpagebreak = 0"]
[er]
[layopt layer=massage0 page=back visible=false]
;”wŒiƒŒƒCƒ„‚Ì•\E— ‰æ–Ê‚É‰æ‘œ‚ğ“Ç‚İ‚Ş
[image storage="CG4_1" layer=base page=fore]
[p]
[image storage="CG4_2" layer=base page=fore]
[p]
[image storage="CG4_3" layer=base page=fore]
[p]
[image storage="CG4_4" layer=base page=fore]
[p]
[wait time=300 mode="normal" canskip=false]
[jump storage="album.ks" target=*album_loop0]

*005|
[rclick jump=true target="*album_menu" storage="album.ks" enabled=true]
[eval exp="sf.showpagebreak = 0"]
[er]
[layopt layer=massage0 page=back visible=false]
;”wŒiƒŒƒCƒ„‚Ì•\E— ‰æ–Ê‚É‰æ‘œ‚ğ“Ç‚İ‚Ş
[image storage="CG5_1" layer=base page=fore]
[p]
[image storage="CG5_2" layer=base page=fore]
[p]
[image storage="CG5_3" layer=base page=fore]
[p]
[image storage="CG5_4" layer=base page=fore]
[p]
[image storage="CG5_5" layer=base page=fore]
[p]
[image storage="CG5_6" layer=base page=fore]
[p]
[wait time=300 mode="normal" canskip=false]
[jump storage="album.ks" target=*album_loop0]

*006|
[rclick jump=true target="*album_menu" storage="album.ks" enabled=true]
[eval exp="sf.showpagebreak = 0"]
[er]
[layopt layer=massage0 page=back visible=false]
;”wŒiƒŒƒCƒ„‚Ì•\E— ‰æ–Ê‚É‰æ‘œ‚ğ“Ç‚İ‚Ş
[image storage="CG6_1" layer=base page=fore]
[p]
[image storage="CG6_2" layer=base page=fore]
[p]
[image storage="CG6_3" layer=base page=fore]
[p]
[image storage="CG6_4" layer=base page=fore]
[p]
[wait time=300 mode="normal" canskip=false]
[jump storage="album.ks" target=*album_loop0]

*007|
[rclick jump=true target="*album_menu" storage="album.ks" enabled=true]
[eval exp="sf.showpagebreak = 0"]
[er]
[layopt layer=massage0 page=back visible=false]
;”wŒiƒŒƒCƒ„‚Ì•\E— ‰æ–Ê‚É‰æ‘œ‚ğ“Ç‚İ‚Ş
[image storage="CG7_1" layer=base page=fore]
[p]
[image storage="CG7_2" layer=base page=fore]
[p]
[image storage="CG7_3" layer=base page=fore]
[p]
[wait time=300 mode="normal" canskip=false]
[jump storage="album.ks" target=*album_loop0]

*008|
[rclick jump=true target="*album_menu" storage="album.ks" enabled=true]
[eval exp="sf.showpagebreak = 0"]
[er]
[layopt layer=massage0 page=back visible=false]
;”wŒiƒŒƒCƒ„‚Ì•\E— ‰æ–Ê‚É‰æ‘œ‚ğ“Ç‚İ‚Ş
[image storage="CG8_1" layer=base page=fore]
[p]
[image storage="CG8_2" layer=base page=fore]
[p]
[image storage="CG8_3" layer=base page=fore]
[p]
[image storage="CG8_4" layer=base page=fore]
[p]
[wait time=300 mode="normal" canskip=false]
[jump storage="album.ks" target=*album_loop0]

*009|
[rclick jump=true target="*album_menu" storage="album.ks" enabled=true]
[eval exp="sf.showpagebreak = 0"]
[er]
[layopt layer=massage0 page=back visible=false]
;”wŒiƒŒƒCƒ„‚Ì•\E— ‰æ–Ê‚É‰æ‘œ‚ğ“Ç‚İ‚Ş
[image storage="CG9_1" layer=base page=fore]
[p]
[image storage="CG9_2" layer=base page=fore]
[p]
[image storage="CG9_3" layer=base page=fore]
[p]
[wait time=300 mode="normal" canskip=false]
[jump storage="album.ks" target=*album_loop0]

*010|
[rclick jump=true target="*album_menu" storage="album.ks" enabled=true]
[eval exp="sf.showpagebreak = 0"]
[er]
[layopt layer=massage0 page=back visible=false]
;”wŒiƒŒƒCƒ„‚Ì•\E— ‰æ–Ê‚É‰æ‘œ‚ğ“Ç‚İ‚Ş
[image storage="CG10_1" layer=base page=fore]
[p]
[image storage="CG10_2" layer=base page=fore]
[p]
[image storage="CG10_3" layer=base page=fore]
[p]
[wait time=300 mode="normal" canskip=false]
[jump storage="album.ks" target=*album_loop0]

*011|
[rclick jump=true target="*album_menu" storage="album.ks" enabled=true]
[eval exp="sf.showpagebreak = 0"]
[er]
[layopt layer=massage0 page=back visible=false]
;”wŒiƒŒƒCƒ„‚Ì•\E— ‰æ–Ê‚É‰æ‘œ‚ğ“Ç‚İ‚Ş
[image storage="CG11_1" layer=base page=fore]
[p]
[image storage="CG11_2" layer=base page=fore]
[p]
[image storage="CG11_3" layer=base page=fore]
[p]
[image storage="CG11_4" layer=base page=fore]
[p]
[image storage="CG11_5" layer=base page=fore]
[p]
[wait time=300 mode="normal" canskip=false]
[jump storage="album.ks" target=*album_loop0]

*012|
[rclick jump=true target="*album_menu" storage="album.ks" enabled=true]
[eval exp="sf.showpagebreak = 0"]
[er]
[layopt layer=massage0 page=back visible=false]
;”wŒiƒŒƒCƒ„‚Ì•\E— ‰æ–Ê‚É‰æ‘œ‚ğ“Ç‚İ‚Ş
[image storage="CG12_1" layer=base page=fore]
[p]
[image storage="CG12_2" layer=base page=fore]
[p]
[image storage="CG12_3" layer=base page=fore]
[p]
[image storage="CG12_4" layer=base page=fore]
[p]
[image storage="CG12_5" layer=base page=fore]
[p]
[wait time=300 mode="normal" canskip=false]
[jump storage="album.ks" target=*album_loop0]

*013|
[rclick jump=true target="*album_menu" storage="album.ks" enabled=true]
[eval exp="sf.showpagebreak = 0"]
[er]
[layopt layer=massage0 page=back visible=false]
;”wŒiƒŒƒCƒ„‚Ì•\E— ‰æ–Ê‚É‰æ‘œ‚ğ“Ç‚İ‚Ş
[image storage="CG13_1" layer=base page=fore]
[p]
[image storage="CG13_2" layer=base page=fore]
[p]
[wait time=300 mode="normal" canskip=false]
[jump storage="album.ks" target=*album_loop0]

*014|
[rclick jump=true target="*album_menu" storage="album.ks" enabled=true]
[eval exp="sf.showpagebreak = 0"]
[er]
[layopt layer=massage0 page=back visible=false]
;”wŒiƒŒƒCƒ„‚Ì•\E— ‰æ–Ê‚É‰æ‘œ‚ğ“Ç‚İ‚Ş
[image storage="CG14_1" layer=base page=fore]
[p]
[image storage="CG14_2" layer=base page=fore]
[p]
[image storage="CG14_3" layer=base page=fore]
[p]
[image storage="CG14_4" layer=base page=fore]
[p]
[image storage="CG14_5" layer=base page=fore]
[p]
[wait time=300 mode="normal" canskip=false]
[jump storage="album.ks" target=*album_loop0]

*015|
[rclick jump=true target="*album_menu" storage="album.ks" enabled=true]
[eval exp="sf.showpagebreak = 0"]
[er]
[layopt layer=massage0 page=back visible=false]
;”wŒiƒŒƒCƒ„‚Ì•\E— ‰æ–Ê‚É‰æ‘œ‚ğ“Ç‚İ‚Ş
[image storage="CG15_1" layer=base page=fore]
[p]
[image storage="CG15_2" layer=base page=fore]
[p]
[image storage="CG15_3" layer=base page=fore]
[p]
[image storage="CG15_4" layer=base page=fore]
[p]
[wait time=300 mode="normal" canskip=false]
[jump storage="album.ks" target=*album_loop0]

*016|
[rclick jump=true target="*album_menu" storage="album.ks" enabled=true]
[eval exp="sf.showpagebreak = 0"]
[er]
[layopt layer=massage0 page=back visible=false]
;”wŒiƒŒƒCƒ„‚Ì•\E— ‰æ–Ê‚É‰æ‘œ‚ğ“Ç‚İ‚Ş
[image storage="CG16_1" layer=base page=fore]
[p]
[image storage="CG16_2" layer=base page=fore]
[p]
[image storage="CG16_3" layer=base page=fore]
[p]
[image storage="CG16_4" layer=base page=fore]
[p]
[wait time=300 mode="normal" canskip=false]
[jump storage="album.ks" target=*album_loop0]

*017|
[rclick jump=true target="*album_menu" storage="album.ks" enabled=true]
[eval exp="sf.showpagebreak = 0"]
[er]
[layopt layer=massage0 page=back visible=false]
;”wŒiƒŒƒCƒ„‚Ì•\E— ‰æ–Ê‚É‰æ‘œ‚ğ“Ç‚İ‚Ş
[image storage="CG17_1" layer=base page=fore]
[p]
[image storage="CG17_2" layer=base page=fore]
[p]
[image storage="CG17_3" layer=base page=fore]
[p]
[wait time=300 mode="normal" canskip=false]
[jump storage="album.ks" target=*album_loop0]

*018|
[rclick jump=true target="*album_menu" storage="album.ks" enabled=true]
[eval exp="sf.showpagebreak = 0"]
[er]
[layopt layer=massage0 page=back visible=false]
;”wŒiƒŒƒCƒ„‚Ì•\E— ‰æ–Ê‚É‰æ‘œ‚ğ“Ç‚İ‚Ş
[image storage="CG18_1" layer=base page=fore]
[p]
[image storage="CG18_2" layer=base page=fore]
[p]
[image storage="CG18_3" layer=base page=fore]
[p]
[wait time=300 mode="normal" canskip=false]
[jump storage="album.ks" target=*album_loop0]

*019|
[rclick jump=true target="*album_menu" storage="album.ks" enabled=true]
[eval exp="sf.showpagebreak = 0"]
[er]
[layopt layer=massage0 page=back visible=false]
;”wŒiƒŒƒCƒ„‚Ì•\E— ‰æ–Ê‚É‰æ‘œ‚ğ“Ç‚İ‚Ş
[image storage="CG19_1" layer=base page=fore]
[p]
[image storage="CG19_2" layer=base page=fore]
[p]
[wait time=300 mode="normal" canskip=false]
[jump storage="album.ks" target=*album_loop0]

*020|
[rclick jump=true target="*album_menu" storage="album.ks" enabled=true]
[eval exp="sf.showpagebreak = 0"]
[er]
[layopt layer=massage0 page=back visible=false]
;”wŒiƒŒƒCƒ„‚Ì•\E— ‰æ–Ê‚É‰æ‘œ‚ğ“Ç‚İ‚Ş
[image storage="CG20_1" layer=base page=fore]
[p]
[image storage="CG20_2" layer=base page=fore]
[p]
[image storage="CG20_3" layer=base page=fore]
[p]
[image storage="CG20_4" layer=base page=fore]
[p]
[wait time=300 mode="normal" canskip=false]
[jump storage="album.ks" target=*album_loop0]

*021|
[rclick jump=true target="*album_menu" storage="album.ks" enabled=true]
[eval exp="sf.showpagebreak = 0"]
[er]
[layopt layer=massage0 page=back visible=false]
;”wŒiƒŒƒCƒ„‚Ì•\E— ‰æ–Ê‚É‰æ‘œ‚ğ“Ç‚İ‚Ş
[image storage="CG21_1_1" layer=base page=fore]
[p]
[image storage="CG21_2_1" layer=base page=fore]
[p]
[image storage="CG21_3_1" layer=base page=fore]
[p]
[image storage="CG21_1_2" layer=base page=fore]
[p]
[image storage="CG21_2_2" layer=base page=fore]
[p]
[image storage="CG21_3_2" layer=base page=fore]
[p]
[wait time=300 mode="normal" canskip=false]
[jump storage="album.ks" target=*album_loop0]

*022|
[rclick jump=true target="*album_menu" storage="album.ks" enabled=true]
[eval exp="sf.showpagebreak = 0"]
[er]
[layopt layer=massage0 page=back visible=false]
;”wŒiƒŒƒCƒ„‚Ì•\E— ‰æ–Ê‚É‰æ‘œ‚ğ“Ç‚İ‚Ş
[image storage="CG22_1_1" layer=base page=fore]
[p]
[image storage="CG22_1_2" layer=base page=fore]
[p]
[image storage="CG22_2_1" layer=base page=fore]
[p]
[image storage="CG22_3_1" layer=base page=fore]
[p]
[image storage="CG22_4_1" layer=base page=fore]
[p]
[image storage="CG22_3_2" layer=base page=fore]
[p]
[image storage="CG22_4_2" layer=base page=fore]
[p]
[wait time=300 mode="normal" canskip=false]
[jump storage="album.ks" target=*album_loop0]

*023|
[rclick jump=true target="*album_menu" storage="album.ks" enabled=true]
[eval exp="sf.showpagebreak = 0"]
[er]
[layopt layer=massage0 page=back visible=false]
;”wŒiƒŒƒCƒ„‚Ì•\E— ‰æ–Ê‚É‰æ‘œ‚ğ“Ç‚İ‚Ş
[image storage="CG23_1_1" layer=base page=fore]
[p]
[image storage="CG23_2_1" layer=base page=fore]
[p]
[image storage="CG23_3_1" layer=base page=fore]
[p]
[image storage="CG23_4_1" layer=base page=fore]
[p]
[image storage="CG23_5_1" layer=base page=fore]
[p]
[image storage="CG23_4_2" layer=base page=fore]
[p]
[image storage="CG23_5_2" layer=base page=fore]
[p]
[wait time=300 mode="normal" canskip=false]
[jump storage="album.ks" target=*album_loop0]

*024|
[rclick jump=true target="*album_menu" storage="album.ks" enabled=true]
[eval exp="sf.showpagebreak = 0"]
[er]
[layopt layer=massage0 page=back visible=false]
;”wŒiƒŒƒCƒ„‚Ì•\E— ‰æ–Ê‚É‰æ‘œ‚ğ“Ç‚İ‚Ş
[image storage="CG24_1" layer=base page=fore]
[p]
[image storage="CG24_2" layer=base page=fore]
[p]
[image storage="CG24_3" layer=base page=fore]
[p]
[wait time=300 mode="normal" canskip=false]
[jump storage="album.ks" target=*album_loop0]

*025|
[rclick jump=true target="*album_menu" storage="album.ks" enabled=true]
[eval exp="sf.showpagebreak = 0"]
[er]
[layopt layer=massage0 page=back visible=false]
;”wŒiƒŒƒCƒ„‚Ì•\E— ‰æ–Ê‚É‰æ‘œ‚ğ“Ç‚İ‚Ş
[image storage="CG25_0_1" layer=base page=fore]
[p]
[image storage="CG25_1_1" layer=base page=fore]
[p]
[image storage="CG25_0_2" layer=base page=fore]
[p]
[image storage="CG25_1_2" layer=base page=fore]
[p]
[image storage="CG25_1_3" layer=base page=fore]
[p]
[image storage="CG25_2_1" layer=base page=fore]
[p]
[image storage="CG25_3_1" layer=base page=fore]
[p]
[image storage="CG25_4_1" layer=base page=fore]
[p]
[image storage="CG25_3_2" layer=base page=fore]
[p]
[image storage="CG25_4_2" layer=base page=fore]
[p]
[wait time=300 mode="normal" canskip=false]
[jump storage="album.ks" target=*album_loop0]

*026|
[rclick jump=true target="*album_menu" storage="album.ks" enabled=true]
[eval exp="sf.showpagebreak = 0"]
[er]
[layopt layer=massage0 page=back visible=false]
;”wŒiƒŒƒCƒ„‚Ì•\E— ‰æ–Ê‚É‰æ‘œ‚ğ“Ç‚İ‚Ş
[image storage="CG26_1_1" layer=base page=fore]
[p]
[image storage="CG26_2_1" layer=base page=fore]
[p]
[image storage="CG26_3_1" layer=base page=fore]
[p]
[image storage="CG26_3_2" layer=base page=fore]
[p]
[image storage="CG26_4_1" layer=base page=fore]
[p]
[image storage="CG26_4_2" layer=base page=fore]
[p]
[wait time=300 mode="normal" canskip=false]
[jump storage="album.ks" target=*album_loop0]

*027|
[rclick jump=true target="*album_menu" storage="album.ks" enabled=true]
[eval exp="sf.showpagebreak = 0"]
[er]
[layopt layer=massage0 page=back visible=false]
;”wŒiƒŒƒCƒ„‚Ì•\E— ‰æ–Ê‚É‰æ‘œ‚ğ“Ç‚İ‚Ş
[image storage="CG27_1" layer=base page=fore]
[p]
[image storage="CG27_2" layer=base page=fore]
[p]
[image storage="CG27_3" layer=base page=fore]
[p]
[image storage="CG27_4" layer=base page=fore]
[p]
[wait time=300 mode="normal" canskip=false]
[jump storage="album.ks" target=*album_loop0]

*028|
[rclick jump=true target="*album_menu" storage="album.ks" enabled=true]
[eval exp="sf.showpagebreak = 0"]
[er]
[layopt layer=massage0 page=back visible=false]
;”wŒiƒŒƒCƒ„‚Ì•\E— ‰æ–Ê‚É‰æ‘œ‚ğ“Ç‚İ‚Ş
[image storage="CG28_0_0" layer=base page=fore]
[p]
[image storage="CG28_0_1" layer=base page=fore]
[p]
[image storage="CG28_0_2" layer=base page=fore]
[p]
[image storage="CG28_1_1" layer=base page=fore]
[p]
[image storage="CG28_1_2" layer=base page=fore]
[p]
[wait time=300 mode="normal" canskip=false]
[jump storage="album.ks" target=*album_loop0]

*029|
[rclick jump=true target="*album_menu" storage="album.ks" enabled=true]
[eval exp="sf.showpagebreak = 0"]
[er]
[layopt layer=massage0 page=back visible=false]
;”wŒiƒŒƒCƒ„‚Ì•\E— ‰æ–Ê‚É‰æ‘œ‚ğ“Ç‚İ‚Ş
[image storage="CG29_1" layer=base page=fore]
[p]
[image storage="CG29_2" layer=base page=fore]
[p]
[image storage="CG29_3" layer=base page=fore]
[p]
[wait time=300 mode="normal" canskip=false]
[jump storage="album.ks" target=*album_loop0]

*030|
[rclick jump=true target="*album_menu" storage="album.ks" enabled=true]
[eval exp="sf.showpagebreak = 0"]
[er]
[layopt layer=massage0 page=back visible=false]
;”wŒiƒŒƒCƒ„‚Ì•\E— ‰æ–Ê‚É‰æ‘œ‚ğ“Ç‚İ‚Ş
[image storage="CG30_0" layer=base page=fore]
[p]
[image storage="CG30_1" layer=base page=fore]
[p]
[image storage="CG30_2" layer=base page=fore]
[p]
[image storage="CG30_3" layer=base page=fore]
[p]
[image storage="CG30_4" layer=base page=fore]
[p]
[image storage="CG30_5" layer=base page=fore]
[p]
[wait time=300 mode="normal" canskip=false]
[jump storage="album.ks" target=*album_loop0]

*031|
[rclick jump=true target="*album_menu" storage="album.ks" enabled=true]
[eval exp="sf.showpagebreak = 0"]
[er]
[layopt layer=massage0 page=back visible=false]
;”wŒiƒŒƒCƒ„‚Ì•\E— ‰æ–Ê‚É‰æ‘œ‚ğ“Ç‚İ‚Ş
[image storage="CG31_1" layer=base page=fore]
[p]
[image storage="CG31_2" layer=base page=fore]
[p]
[image storage="CG31_3" layer=base page=fore]
[p]
[image storage="CG31_4" layer=base page=fore]
[p]
[wait time=300 mode="normal" canskip=false]
[jump storage="album.ks" target=*album_loop0]

*032|
[rclick jump=true target="*album_menu" storage="album.ks" enabled=true]
[eval exp="sf.showpagebreak = 0"]
[er]
[layopt layer=massage0 page=back visible=false]
;”wŒiƒŒƒCƒ„‚Ì•\E— ‰æ–Ê‚É‰æ‘œ‚ğ“Ç‚İ‚Ş
[image storage="CG32_1" layer=base page=fore]
[p]
[image storage="CG32_2" layer=base page=fore]
[p]
[image storage="CG32_3" layer=base page=fore]
[p]
[wait time=300 mode="normal" canskip=false]
[jump storage="album.ks" target=*album_loop0]

*033|
[rclick jump=true target="*album_menu" storage="album.ks" enabled=true]
[eval exp="sf.showpagebreak = 0"]
[er]
[layopt layer=massage0 page=back visible=false]
;”wŒiƒŒƒCƒ„‚Ì•\E— ‰æ–Ê‚É‰æ‘œ‚ğ“Ç‚İ‚Ş
[image storage="CG33_1" layer=base page=fore]
[p]
[image storage="CG33_2" layer=base page=fore]
[p]
[image storage="CG33_3" layer=base page=fore]
[p]
[image storage="CG33_4" layer=base page=fore]
[p]
[wait time=300 mode="normal" canskip=false]
[jump storage="album.ks" target=*album_loop0]

*034|
[rclick jump=true target="*album_menu" storage="album.ks" enabled=true]
[eval exp="sf.showpagebreak = 0"]
[er]
[layopt layer=massage0 page=back visible=false]
;”wŒiƒŒƒCƒ„‚Ì•\E— ‰æ–Ê‚É‰æ‘œ‚ğ“Ç‚İ‚Ş
[image storage="CG34_1" layer=base page=fore]
[p]
[image storage="CG34_2" layer=base page=fore]
[p]
[image storage="CG34_3" layer=base page=fore]
[p]
[wait time=300 mode="normal" canskip=false]
[jump storage="album.ks" target=*album_loop0]

*035|
[rclick jump=true target="*album_menu" storage="album.ks" enabled=true]
[eval exp="sf.showpagebreak = 0"]
[er]
[layopt layer=massage0 page=back visible=false]
;”wŒiƒŒƒCƒ„‚Ì•\E— ‰æ–Ê‚É‰æ‘œ‚ğ“Ç‚İ‚Ş
[image storage="CG35_1_1" layer=base page=fore]
[p]
[image storage="CG35_2_1" layer=base page=fore]
[p]
[image storage="CG35_2_2" layer=base page=fore]
[p]
[image storage="CG35_3_1" layer=base page=fore]
[p]
[image storage="CG35_3_2" layer=base page=fore]
[p]
[wait time=300 mode="normal" canskip=false]
[jump storage="album.ks" target=*album_loop0]

*036|
[rclick jump=true target="*album_menu" storage="album.ks" enabled=true]
[eval exp="sf.showpagebreak = 0"]
[er]
[layopt layer=massage0 page=back visible=false]
;”wŒiƒŒƒCƒ„‚Ì•\E— ‰æ–Ê‚É‰æ‘œ‚ğ“Ç‚İ‚Ş
[image storage="CG36_1" layer=base page=fore]
[p]
[image storage="CG36_2_1" layer=base page=fore]
[p]
[image storage="CG36_2_2" layer=base page=fore]
[p]
[image storage="CG36_3_1" layer=base page=fore]
[p]
[image storage="CG36_3_2" layer=base page=fore]
[p]
[image storage="CG36_4_1" layer=base page=fore]
[p]
[image storage="CG36_4_2" layer=base page=fore]
[p]
[wait time=300 mode="normal" canskip=false]
[jump storage="album.ks" target=*album_loop0]

*037|
[rclick jump=true target="*album_menu" storage="album.ks" enabled=true]
[eval exp="sf.showpagebreak = 0"]
[er]
[layopt layer=massage0 page=back visible=false]
;”wŒiƒŒƒCƒ„‚Ì•\E— ‰æ–Ê‚É‰æ‘œ‚ğ“Ç‚İ‚Ş
[image storage="CG37_1_1" layer=base page=fore]
[p]
[image storage="CG37_2_1" layer=base page=fore]
[p]
[image storage="CG37_2_2" layer=base page=fore]
[p]
[image storage="CG37_3_1" layer=base page=fore]
[p]
[image storage="CG37_4_1" layer=base page=fore]
[p]
[image storage="CG37_5_1" layer=base page=fore]
[p]
[image storage="CG37_5_2" layer=base page=fore]
[p]
[image storage="CG37_6_1" layer=base page=fore]
[p]
[wait time=300 mode="normal" canskip=false]
[jump storage="album.ks" target=*album_loop0]

*038|
[rclick jump=true target="*album_menu" storage="album.ks" enabled=true]
[eval exp="sf.showpagebreak = 0"]
[er]
[layopt layer=massage0 page=back visible=false]
;”wŒiƒŒƒCƒ„‚Ì•\E— ‰æ–Ê‚É‰æ‘œ‚ğ“Ç‚İ‚Ş
[image storage="CG38_1_1" layer=base page=fore]
[p]
[image storage="CG38_2_1" layer=base page=fore]
[p]
[image storage="CG38_2_2" layer=base page=fore]
[p]
[image storage="CG38_3_1" layer=base page=fore]
[p]
[image storage="CG38_3_2" layer=base page=fore]
[p]
[image storage="CG38_4_1" layer=base page=fore]
[p]
[image storage="CG38_4_2" layer=base page=fore]
[p]
[wait time=300 mode="normal" canskip=false]
[jump storage="album.ks" target=*album_loop0]

*039|
[rclick jump=true target="*album_menu" storage="album.ks" enabled=true]
[eval exp="sf.showpagebreak = 0"]
[er]
[layopt layer=massage0 page=back visible=false]
;”wŒiƒŒƒCƒ„‚Ì•\E— ‰æ–Ê‚É‰æ‘œ‚ğ“Ç‚İ‚Ş
[image storage="CG39_0_1" layer=base page=fore]
[p]
[image storage="CG39_1_1" layer=base page=fore]
[p]
[image storage="CG39_1_2" layer=base page=fore]
[p]
[image storage="CG39_2_1" layer=base page=fore]
[p]
[image storage="CG39_3_1" layer=base page=fore]
[p]
[image storage="CG39_4_1" layer=base page=fore]
[p]
[image storage="CG39_4_2" layer=base page=fore]
[p]
[image storage="CG39_5_1" layer=base page=fore]
[p]
[image storage="CG39_5_2" layer=base page=fore]
[p]
[wait time=300 mode="normal" canskip=false]
[jump storage="album.ks" target=*album_loop0]

*040|
[rclick jump=true target="*album_menu" storage="album.ks" enabled=true]
[eval exp="sf.showpagebreak = 0"]
[er]
[layopt layer=massage0 page=back visible=false]
;”wŒiƒŒƒCƒ„‚Ì•\E— ‰æ–Ê‚É‰æ‘œ‚ğ“Ç‚İ‚Ş
[image storage="CG40_0_1" layer=base page=fore]
[p]
[image storage="CG40_1_1" layer=base page=fore]
[p]
[image storage="CG40_2_1" layer=base page=fore]
[p]
[image storage="CG40_3_1" layer=base page=fore]
[p]
[image storage="CG40_3_2" layer=base page=fore]
[p]
[image storage="CG40_4_1" layer=base page=fore]
[p]
[image storage="CG40_4_2" layer=base page=fore]
[p]
[image storage="CG40_5_1" layer=base page=fore]
[p]
[image storage="CG40_5_2" layer=base page=fore]
[p]
[wait time=300 mode="normal" canskip=false]
[jump storage="album.ks" target=*album_loop0]

*041|
[rclick jump=true target="*album_menu" storage="album.ks" enabled=true]
[eval exp="sf.showpagebreak = 0"]
[er]
[layopt layer=massage0 page=back visible=false]
;”wŒiƒŒƒCƒ„‚Ì•\E— ‰æ–Ê‚É‰æ‘œ‚ğ“Ç‚İ‚Ş
[image storage="CG41_1" layer=base page=fore]
[p]
[image storage="CG41_2" layer=base page=fore]
[p]
[image storage="CG41_3" layer=base page=fore]
[p]
[wait time=300 mode="normal" canskip=false]
[jump storage="album.ks" target=*album_loop0]

*042|
[rclick jump=true target="*album_menu" storage="album.ks" enabled=true]
[eval exp="sf.showpagebreak = 0"]
[er]
[layopt layer=massage0 page=back visible=false]
;”wŒiƒŒƒCƒ„‚Ì•\E— ‰æ–Ê‚É‰æ‘œ‚ğ“Ç‚İ‚Ş
[image storage="CG42_0_0" layer=base page=fore]
[p]
[image storage="CG42_1_0" layer=base page=fore]
[p]
[image storage="CG42_0_1" layer=base page=fore]
[p]
[image storage="CG42_1_1" layer=base page=fore]
[p]
[image storage="CG42_2_1" layer=base page=fore]
[p]
[image storage="CG42_2_2" layer=base page=fore]
[p]
[image storage="CG42_3_1" layer=base page=fore]
[p]
[image storage="CG42_4_1" layer=base page=fore]
[p]
[image storage="CG42_5_1" layer=base page=fore]
[p]
[wait time=300 mode="normal" canskip=false]
[jump storage="album.ks" target=*album_loop0]

*043|
[rclick jump=true target="*album_menu" storage="album.ks" enabled=true]
[eval exp="sf.showpagebreak = 0"]
[er]
[layopt layer=massage0 page=back visible=false]
;”wŒiƒŒƒCƒ„‚Ì•\E— ‰æ–Ê‚É‰æ‘œ‚ğ“Ç‚İ‚Ş
[image storage="CG43_1_1" layer=base page=fore]
[p]
[image storage="CG43_2_1" layer=base page=fore]
[p]
[image storage="CG43_1_2" layer=base page=fore]
[p]
[image storage="CG43_2_2" layer=base page=fore]
[p]
[image storage="CG43_3_1" layer=base page=fore]
[p]
[image storage="CG43_4_1" layer=base page=fore]
[p]
[image storage="CG43_5_1" layer=base page=fore]
[p]
[image storage="CG43_4_2" layer=base page=fore]
[p]
[image storage="CG43_5_2" layer=base page=fore]
[p]
[wait time=300 mode="normal" canskip=false]
[jump storage="album.ks" target=*album_loop0]

*044|
[rclick jump=true target="*album_menu" storage="album.ks" enabled=true]
[eval exp="sf.showpagebreak = 0"]
[er]
[layopt layer=massage0 page=back visible=false]
;”wŒiƒŒƒCƒ„‚Ì•\E— ‰æ–Ê‚É‰æ‘œ‚ğ“Ç‚İ‚Ş
[image storage="CG44_1" layer=base page=fore]
[p]
[image storage="CG44_2" layer=base page=fore]
[p]
[image storage="CG44_3" layer=base page=fore]
[p]
[image storage="CG44_4" layer=base page=fore]
[p]
[wait time=300 mode="normal" canskip=false]
[jump storage="album.ks" target=*album_loop0]

*045|
[rclick jump=true target="*album_menu" storage="album.ks" enabled=true]
[eval exp="sf.showpagebreak = 0"]
[er]
[layopt layer=massage0 page=back visible=false]
;”wŒiƒŒƒCƒ„‚Ì•\E— ‰æ–Ê‚É‰æ‘œ‚ğ“Ç‚İ‚Ş
[image storage="CG45_1" layer=base page=fore]
[p]
[image storage="CG45_2" layer=base page=fore]
[p]
[image storage="CG45_3" layer=base page=fore]
[p]
[image storage="CG45_4" layer=base page=fore]
[p]
[wait time=300 mode="normal" canskip=false]
[jump storage="album.ks" target=*album_loop0]

*046|
[rclick jump=true target="*album_menu" storage="album.ks" enabled=true]
[eval exp="sf.showpagebreak = 0"]
[er]
[layopt layer=massage0 page=back visible=false]
;”wŒiƒŒƒCƒ„‚Ì•\E— ‰æ–Ê‚É‰æ‘œ‚ğ“Ç‚İ‚Ş
[image storage="CG46_1" layer=base page=fore]
[p]
[image storage="CG46_2" layer=base page=fore]
[p]
[image storage="CG46_3" layer=base page=fore]
[p]
[image storage="CG46_4" layer=base page=fore]
[p]
[image storage="CG46_5" layer=base page=fore]
[p]
[wait time=300 mode="normal" canskip=false]
[jump storage="album.ks" target=*album_loop0]

*047|
[rclick jump=true target="*album_menu" storage="album.ks" enabled=true]
[eval exp="sf.showpagebreak = 0"]
[er]
[layopt layer=massage0 page=back visible=false]
;”wŒiƒŒƒCƒ„‚Ì•\E— ‰æ–Ê‚É‰æ‘œ‚ğ“Ç‚İ‚Ş
[image storage="CG47_0" layer=base page=fore]
[p]
[image storage="CG47_1" layer=base page=fore]
[p]
[image storage="CG47_2" layer=base page=fore]
[p]
[image storage="CG47_3" layer=base page=fore]
[p]
[image storage="CG47_4" layer=base page=fore]
[p]
[wait time=300 mode="normal" canskip=false]
[jump storage="album.ks" target=*album_loop0]

*048|
[rclick jump=true target="*album_menu" storage="album.ks" enabled=true]
[eval exp="sf.showpagebreak = 0"]
[er]
[layopt layer=massage0 page=back visible=false]
;”wŒiƒŒƒCƒ„‚Ì•\E— ‰æ–Ê‚É‰æ‘œ‚ğ“Ç‚İ‚Ş
[image storage="CG48_0" layer=base page=fore]
[p]
[image storage="CG48_1" layer=base page=fore]
[p]
[image storage="CG48_2" layer=base page=fore]
[p]
[image storage="CG48_3" layer=base page=fore]
[p]
[wait time=300 mode="normal" canskip=false]
[jump storage="album.ks" target=*album_loop0]

*049|
[rclick jump=true target="*album_menu" storage="album.ks" enabled=true]
[eval exp="sf.showpagebreak = 0"]
[er]
[layopt layer=massage0 page=back visible=false]
;”wŒiƒŒƒCƒ„‚Ì•\E— ‰æ–Ê‚É‰æ‘œ‚ğ“Ç‚İ‚Ş
[image storage="CG49_0" layer=base page=fore]
[p]
[image storage="CG49_1" layer=base page=fore]
[p]
[image storage="CG49_2" layer=base page=fore]
[p]
[image storage="CG49_3" layer=base page=fore]
[p]
[image storage="CG49_4" layer=base page=fore]
[p]
[image storage="CG49_5" layer=base page=fore]
[p]
[wait time=300 mode="normal" canskip=false]
[jump storage="album.ks" target=*album_loop0]

*050|
[rclick jump=true target="*album_menu" storage="album.ks" enabled=true]
[eval exp="sf.showpagebreak = 0"]
[er]
[layopt layer=massage0 page=back visible=false]
;”wŒiƒŒƒCƒ„‚Ì•\E— ‰æ–Ê‚É‰æ‘œ‚ğ“Ç‚İ‚Ş
[image storage="CG50_0" layer=base page=fore]
[p]
[image storage="CG50_1" layer=base page=fore]
[p]
[image storage="CG50_2" layer=base page=fore]
[p]
[image storage="CG50_3" layer=base page=fore]
[p]
[image storage="CG50_4" layer=base page=fore]
[p]
[wait time=300 mode="normal" canskip=false]
[jump storage="album.ks" target=*album_loop0]

*051|
[rclick jump=true target="*album_menu" storage="album.ks" enabled=true]
[eval exp="sf.showpagebreak = 0"]
[er]
[layopt layer=massage0 page=back visible=false]
;”wŒiƒŒƒCƒ„‚Ì•\E— ‰æ–Ê‚É‰æ‘œ‚ğ“Ç‚İ‚Ş
[image storage="CG51_0" layer=base page=fore]
[p]
[image storage="CG51_1" layer=base page=fore]
[p]
[image storage="CG51_2" layer=base page=fore]
[p]
[image storage="CG51_3" layer=base page=fore]
[p]
[image storage="CG51_4" layer=base page=fore]
[p]
[wait time=300 mode="normal" canskip=false]
[jump storage="album.ks" target=*album_loop0]

*052|
[rclick jump=true target="*album_menu" storage="album.ks" enabled=true]
[eval exp="sf.showpagebreak = 0"]
[er]
[layopt layer=massage0 page=back visible=false]
;”wŒiƒŒƒCƒ„‚Ì•\E— ‰æ–Ê‚É‰æ‘œ‚ğ“Ç‚İ‚Ş
[image storage="CG52_0" layer=base page=fore]
[p]
[image storage="CG52_1" layer=base page=fore]
[p]
[image storage="CG52_2" layer=base page=fore]
[p]
[image storage="CG52_3" layer=base page=fore]
[p]
[wait time=300 mode="normal" canskip=false]
[jump storage="album.ks" target=*album_loop0]

*053|
[rclick jump=true target="*album_menu" storage="album.ks" enabled=true]
[eval exp="sf.showpagebreak = 0"]
[er]
[layopt layer=massage0 page=back visible=false]
;”wŒiƒŒƒCƒ„‚Ì•\E— ‰æ–Ê‚É‰æ‘œ‚ğ“Ç‚İ‚Ş
[image storage="CG53_0" layer=base page=fore]
[p]
[image storage="CG53_1" layer=base page=fore]
[p]
[image storage="CG53_2" layer=base page=fore]
[p]
[wait time=300 mode="normal" canskip=false]
[jump storage="album.ks" target=*album_loop0]

*054|
[rclick jump=true target="*album_menu" storage="album.ks" enabled=true]
[eval exp="sf.showpagebreak = 0"]
[er]
[layopt layer=massage0 page=back visible=false]
;”wŒiƒŒƒCƒ„‚Ì•\E— ‰æ–Ê‚É‰æ‘œ‚ğ“Ç‚İ‚Ş
[image storage="CG54_1" layer=base page=fore]
[p]
[image storage="CG54_2" layer=base page=fore]
[p]
[image storage="CG54_3" layer=base page=fore]
[p]
[image storage="CG54_4" layer=base page=fore]
[p]
[wait time=300 mode="normal" canskip=false]
[jump storage="album.ks" target=*album_loop0]

*055|
[rclick jump=true target="*album_menu" storage="album.ks" enabled=true]
[eval exp="sf.showpagebreak = 0"]
[er]
[layopt layer=massage0 page=back visible=false]
;”wŒiƒŒƒCƒ„‚Ì•\E— ‰æ–Ê‚É‰æ‘œ‚ğ“Ç‚İ‚Ş
[image storage="CG55_0" layer=base page=fore]
[p]
[image storage="CG55_1" layer=base page=fore]
[p]
[image storage="CG55_2" layer=base page=fore]
[p]
[image storage="CG55_3" layer=base page=fore]
[p]
[image storage="CG55_4" layer=base page=fore]
[p]
[wait time=300 mode="normal" canskip=false]
[jump storage="album.ks" target=*album_loop0]

*056|
[rclick jump=true target="*album_menu" storage="album.ks" enabled=true]
[eval exp="sf.showpagebreak = 0"]
[er]
[layopt layer=massage0 page=back visible=false]
;”wŒiƒŒƒCƒ„‚Ì•\E— ‰æ–Ê‚É‰æ‘œ‚ğ“Ç‚İ‚Ş
[image storage="CG56_1" layer=base page=fore]
[p]
[image storage="CG56_2" layer=base page=fore]
[p]
[image storage="CG56_3" layer=base page=fore]
[p]
[wait time=300 mode="normal" canskip=false]
[jump storage="album.ks" target=*album_loop0]

*057|
[rclick jump=true target="*album_menu" storage="album.ks" enabled=true]
[eval exp="sf.showpagebreak = 0"]
[er]
[layopt layer=massage0 page=back visible=false]
;”wŒiƒŒƒCƒ„‚Ì•\E— ‰æ–Ê‚É‰æ‘œ‚ğ“Ç‚İ‚Ş
[image storage="CG57_0" layer=base page=fore]
[p]
[image storage="CG57_1" layer=base page=fore]
[p]
[image storage="CG57_2" layer=base page=fore]
[p]
[wait time=300 mode="normal" canskip=false]
[jump storage="album.ks" target=*album_loop0]

*058|
[rclick jump=true target="*album_menu" storage="album.ks" enabled=true]
[eval exp="sf.showpagebreak = 0"]
[er]
[layopt layer=massage0 page=back visible=false]
;”wŒiƒŒƒCƒ„‚Ì•\E— ‰æ–Ê‚É‰æ‘œ‚ğ“Ç‚İ‚Ş
[image storage="CG58_1" layer=base page=fore]
[p]
[image storage="CG58_2" layer=base page=fore]
[p]
[image storage="CG58_3" layer=base page=fore]
[p]
[image storage="CG58_4" layer=base page=fore]
[p]
[image storage="CG58_5" layer=base page=fore]
[p]
[wait time=300 mode="normal" canskip=false]
[jump storage="album.ks" target=*album_loop0]

*059|
[rclick jump=true target="*album_menu" storage="album.ks" enabled=true]
[eval exp="sf.showpagebreak = 0"]
[er]
[layopt layer=massage0 page=back visible=false]
;”wŒiƒŒƒCƒ„‚Ì•\E— ‰æ–Ê‚É‰æ‘œ‚ğ“Ç‚İ‚Ş
[image storage="CG59_1" layer=base page=fore]
[p]
[image storage="CG59_2" layer=base page=fore]
[p]
[image storage="CG59_3" layer=base page=fore]
[p]
[image storage="CG59_4" layer=base page=fore]
[p]
[image storage="CG59_5" layer=base page=fore]
[p]
[wait time=300 mode="normal" canskip=false]
[jump storage="album.ks" target=*album_loop0]

*060|
[rclick jump=true target="*album_menu" storage="album.ks" enabled=true]
[eval exp="sf.showpagebreak = 0"]
[er]
[layopt layer=massage0 page=back visible=false]
;”wŒiƒŒƒCƒ„‚Ì•\E— ‰æ–Ê‚É‰æ‘œ‚ğ“Ç‚İ‚Ş
[image storage="CG60_1" layer=base page=fore]
[p]
[image storage="CG60_2" layer=base page=fore]
[p]
[wait time=300 mode="normal" canskip=false]
[jump storage="album.ks" target=*album_loop0]

*061|
[rclick jump=true target="*album_menu" storage="album.ks" enabled=true]
[eval exp="sf.showpagebreak = 0"]
[er]
[layopt layer=massage0 page=back visible=false]
;”wŒiƒŒƒCƒ„‚Ì•\E— ‰æ–Ê‚É‰æ‘œ‚ğ“Ç‚İ‚Ş
[image storage="CG61_1" layer=base page=fore]
[p]
[image storage="CG61_2" layer=base page=fore]
[p]
[image storage="CG61_3" layer=base page=fore]
[p]
[image storage="CG61_4" layer=base page=fore]
[p]
[wait time=300 mode="normal" canskip=false]
[jump storage="album.ks" target=*album_loop0]

*062|
[rclick jump=true target="*album_menu" storage="album.ks" enabled=true]
[eval exp="sf.showpagebreak = 0"]
[er]
[layopt layer=massage0 page=back visible=false]
;”wŒiƒŒƒCƒ„‚Ì•\E— ‰æ–Ê‚É‰æ‘œ‚ğ“Ç‚İ‚Ş
[image storage="CG62_1" layer=base page=fore]
[p]
[image storage="CG62_2" layer=base page=fore]
[p]
[image storage="CG62_3" layer=base page=fore]
[p]
[wait time=300 mode="normal" canskip=false]
[jump storage="album.ks" target=*album_loop0]

*063|
[rclick jump=true target="*album_menu" storage="album.ks" enabled=true]
[eval exp="sf.showpagebreak = 0"]
[er]
[layopt layer=massage0 page=back visible=false]
;”wŒiƒŒƒCƒ„‚Ì•\E— ‰æ–Ê‚É‰æ‘œ‚ğ“Ç‚İ‚Ş
[image storage="CG63_1" layer=base page=fore]
[p]
[image storage="CG63_2" layer=base page=fore]
[p]
[image storage="CG63_3" layer=base page=fore]
[p]
[image storage="CG63_4" layer=base page=fore]
[p]
[image storage="CG63_5" layer=base page=fore]
[p]
[image storage="CG63_6" layer=base page=fore]
[p]
[wait time=300 mode="normal" canskip=false]
[jump storage="album.ks" target=*album_loop0]

*064|
[rclick jump=true target="*album_menu" storage="album.ks" enabled=true]
[eval exp="sf.showpagebreak = 0"]
[er]
[layopt layer=massage0 page=back visible=false]
;”wŒiƒŒƒCƒ„‚Ì•\E— ‰æ–Ê‚É‰æ‘œ‚ğ“Ç‚İ‚Ş
[image storage="CG64_0" layer=base page=fore]
[p]
[image storage="CG64_1" layer=base page=fore]
[p]
[image storage="CG64_2" layer=base page=fore]
[p]
[image storage="CG64_3" layer=base page=fore]
[p]
[image storage="CG64_4" layer=base page=fore]
[p]
[image storage="CG64_5" layer=base page=fore]
[p]
[wait time=300 mode="normal" canskip=false]
[jump storage="album.ks" target=*album_loop0]

*065|
[rclick jump=true target="*album_menu" storage="album.ks" enabled=true]
[eval exp="sf.showpagebreak = 0"]
[er]
[layopt layer=massage0 page=back visible=false]
;”wŒiƒŒƒCƒ„‚Ì•\E— ‰æ–Ê‚É‰æ‘œ‚ğ“Ç‚İ‚Ş
[image storage="CG65_0" layer=base page=fore]
[p]
[image storage="CG65_1" layer=base page=fore]
[p]
[image storage="CG65_2" layer=base page=fore]
[p]
[image storage="CG65_3" layer=base page=fore]
[p]
[image storage="CG65_4" layer=base page=fore]
[p]
[image storage="CG65_5" layer=base page=fore]
[p]
[wait time=300 mode="normal" canskip=false]
[jump storage="album.ks" target=*album_loop0]

*066|
[rclick jump=true target="*album_menu" storage="album.ks" enabled=true]
[eval exp="sf.showpagebreak = 0"]
[er]
[layopt layer=massage0 page=back visible=false]
;”wŒiƒŒƒCƒ„‚Ì•\E— ‰æ–Ê‚É‰æ‘œ‚ğ“Ç‚İ‚Ş
[image storage="CG66_0" layer=base page=fore]
[p]
[image storage="CG66_1" layer=base page=fore]
[p]
[image storage="CG66_2" layer=base page=fore]
[p]
[image storage="CG66_3" layer=base page=fore]
[p]
[wait time=300 mode="normal" canskip=false]
[jump storage="album.ks" target=*album_loop0]

*067|
[rclick jump=true target="*album_menu" storage="album.ks" enabled=true]
[eval exp="sf.showpagebreak = 0"]
[er]
[layopt layer=massage0 page=back visible=false]
;”wŒiƒŒƒCƒ„‚Ì•\E— ‰æ–Ê‚É‰æ‘œ‚ğ“Ç‚İ‚Ş
[image storage="CG67_0" layer=base page=fore]
[p]
[image storage="CG67_1" layer=base page=fore]
[p]
[image storage="CG67_2" layer=base page=fore]
[p]
[image storage="CG67_3" layer=base page=fore]
[p]
[wait time=300 mode="normal" canskip=false]
[jump storage="album.ks" target=*album_loop0]

*068|
[rclick jump=true target="*album_menu" storage="album.ks" enabled=true]
[eval exp="sf.showpagebreak = 0"]
[er]
[layopt layer=massage0 page=back visible=false]
;”wŒiƒŒƒCƒ„‚Ì•\E— ‰æ–Ê‚É‰æ‘œ‚ğ“Ç‚İ‚Ş
[image storage="CG68_1" layer=base page=fore]
[p]
[image storage="CG68_2" layer=base page=fore]
[p]
[image storage="CG68_3" layer=base page=fore]
[p]
[image storage="CG68_4" layer=base page=fore]
[p]
[image storage="CG68_5" layer=base page=fore]
[p]
[image storage="CG68_6" layer=base page=fore]
[p]
[wait time=300 mode="normal" canskip=false]
[jump storage="album.ks" target=*album_loop0]

*069|
[rclick jump=true target="*album_menu" storage="album.ks" enabled=true]
[eval exp="sf.showpagebreak = 0"]
[er]
[layopt layer=massage0 page=back visible=false]
;”wŒiƒŒƒCƒ„‚Ì•\E— ‰æ–Ê‚É‰æ‘œ‚ğ“Ç‚İ‚Ş
[image storage="CG69_0-0" layer=base page=fore]
[p]
[image storage="CG69_0-1" layer=base page=fore]
[p]
[image storage="CG69_1-0" layer=base page=fore]
[p]
[image storage="CG69_1-1" layer=base page=fore]
[p]
[image storage="CG69_1-2" layer=base page=fore]
[p]
[image storage="CG69_2-2" layer=base page=fore]
[p]
[image storage="CG69_3-0" layer=base page=fore]
[p]
[image storage="CG69_3-1" layer=base page=fore]
[p]
[image storage="CG69_3-2" layer=base page=fore]
[p]
[image storage="CG69_3-3" layer=base page=fore]
[p]
[image storage="CG69_4-3" layer=base page=fore]
[p]
[image storage="CG69_4-4" layer=base page=fore]
[p]
[wait time=300 mode="normal" canskip=false]
[jump storage="album.ks" target=*album_loop0]

*070|
[rclick jump=true target="*album_menu" storage="album.ks" enabled=true]
[eval exp="sf.showpagebreak = 0"]
[er]
[layopt layer=massage0 page=back visible=false]
;”wŒiƒŒƒCƒ„‚Ì•\E— ‰æ–Ê‚É‰æ‘œ‚ğ“Ç‚İ‚Ş
[image storage="CG70_0_1" layer=base page=fore]
[p]
[image storage="CG70_1_1" layer=base page=fore]
[p]
[image storage="CG70_2_1" layer=base page=fore]
[p]
[image storage="CG70_3_1" layer=base page=fore]
[p]
[image storage="CG70_4_1" layer=base page=fore]
[p]
[image storage="CG70_5_1" layer=base page=fore]
[p]
[image storage="CG70_5_2" layer=base page=fore]
[p]
[wait time=300 mode="normal" canskip=false]
[jump storage="album.ks" target=*album_loop0]

*071|
[rclick jump=true target="*album_menu" storage="album.ks" enabled=true]
[eval exp="sf.showpagebreak = 0"]
[er]
[layopt layer=massage0 page=back visible=false]
;”wŒiƒŒƒCƒ„‚Ì•\E— ‰æ–Ê‚É‰æ‘œ‚ğ“Ç‚İ‚Ş
[image storage="CG71_0_1" layer=base page=fore]
[p]
[image storage="CG71_1_1" layer=base page=fore]
[p]
[image storage="CG71_2_1" layer=base page=fore]
[p]
[image storage="CG71_3_1" layer=base page=fore]
[p]
[image storage="CG71_4_1" layer=base page=fore]
[p]
[image storage="CG71_4_2" layer=base page=fore]
[p]
[image storage="CG71_5_1" layer=base page=fore]
[p]
[wait time=300 mode="normal" canskip=false]
[jump storage="album.ks" target=*album_loop0]

*072|
[rclick jump=true target="*album_menu" storage="album.ks" enabled=true]
[eval exp="sf.showpagebreak = 0"]
[er]
[layopt layer=massage0 page=back visible=false]
;”wŒiƒŒƒCƒ„‚Ì•\E— ‰æ–Ê‚É‰æ‘œ‚ğ“Ç‚İ‚Ş
[image storage="CG72_0" layer=base page=fore]
[p]
[image storage="CG72_1" layer=base page=fore]
[p]
[image storage="CG72_2" layer=base page=fore]
[p]
[image storage="CG72_3" layer=base page=fore]
[p]
[image storage="CG72_4" layer=base page=fore]
[p]
[wait time=300 mode="normal" canskip=false]
[jump storage="album.ks" target=*album_loop0]

*073|
[rclick jump=true target="*album_menu" storage="album.ks" enabled=true]
[eval exp="sf.showpagebreak = 0"]
[er]
[layopt layer=massage0 page=back visible=false]
;”wŒiƒŒƒCƒ„‚Ì•\E— ‰æ–Ê‚É‰æ‘œ‚ğ“Ç‚İ‚Ş
[image storage="CG73_0_1" layer=base page=fore]
[p]
[image storage="CG73_1_1" layer=base page=fore]
[p]
[image storage="CG73_2_1" layer=base page=fore]
[p]
[image storage="CG73_2_2" layer=base page=fore]
[p]
[image storage="CG73_3_1" layer=base page=fore]
[p]
[image storage="CG73_4_1" layer=base page=fore]
[p]
[image storage="CG73_5_1" layer=base page=fore]
[p]
[image storage="CG73_4_2" layer=base page=fore]
[p]
[image storage="CG73_5_2" layer=base page=fore]
[p]
[wait time=300 mode="normal" canskip=false]
[jump storage="album.ks" target=*album_loop0]

*074|
[rclick jump=true target="*album_menu" storage="album.ks" enabled=true]
[eval exp="sf.showpagebreak = 0"]
[er]
[layopt layer=massage0 page=back visible=false]
;”wŒiƒŒƒCƒ„‚Ì•\E— ‰æ–Ê‚É‰æ‘œ‚ğ“Ç‚İ‚Ş
[image storage="CG74_1_1" layer=base page=fore]
[p]
[image storage="CG74_2_1" layer=base page=fore]
[p]
[image storage="CG74_3_1" layer=base page=fore]
[p]
[image storage="CG74_4_1" layer=base page=fore]
[p]
[image storage="CG74_3_2" layer=base page=fore]
[p]
[image storage="CG74_4_2" layer=base page=fore]
[p]
[wait time=300 mode="normal" canskip=false]
[jump storage="album.ks" target=*album_loop0]

*075|
[rclick jump=true target="*album_menu" storage="album.ks" enabled=true]
[eval exp="sf.showpagebreak = 0"]
[er]
[layopt layer=massage0 page=back visible=false]
;”wŒiƒŒƒCƒ„‚Ì•\E— ‰æ–Ê‚É‰æ‘œ‚ğ“Ç‚İ‚Ş
[image storage="CG75_0_1" layer=base page=fore]
[p]
[image storage="CG75_1_1" layer=base page=fore]
[p]
[image storage="CG75_1_2" layer=base page=fore]
[p]
[image storage="CG75_2_1" layer=base page=fore]
[p]
[image storage="CG75_3_1" layer=base page=fore]
[p]
[image storage="CG75_4_1" layer=base page=fore]
[p]
[image storage="CG75_1_3" layer=base page=fore]
[p]
[image storage="CG75_4_2" layer=base page=fore]
[p]
[wait time=300 mode="normal" canskip=false]
[jump storage="album.ks" target=*album_loop0]

*076|
[rclick jump=true target="*album_menu" storage="album.ks" enabled=true]
[eval exp="sf.showpagebreak = 0"]
[er]
[layopt layer=massage0 page=back visible=false]
;”wŒiƒŒƒCƒ„‚Ì•\E— ‰æ–Ê‚É‰æ‘œ‚ğ“Ç‚İ‚Ş
[image storage="CG76_0_1" layer=base page=fore]
[p]
[image storage="CG76_1_1" layer=base page=fore]
[p]
[image storage="CG76_2_1" layer=base page=fore]
[p]
[image storage="CG76_3_1" layer=base page=fore]
[p]
[image storage="CG76_4_1" layer=base page=fore]
[p]
[image storage="CG76_5_1" layer=base page=fore]
[p]
[image storage="CG76_4_2" layer=base page=fore]
[p]
[image storage="CG76_5_2" layer=base page=fore]
[p]
[wait time=300 mode="normal" canskip=false]
[jump storage="album.ks" target=*album_loop0]

*077|
[rclick jump=true target="*album_menu" storage="album.ks" enabled=true]
[eval exp="sf.showpagebreak = 0"]
[er]
[layopt layer=massage0 page=back visible=false]
;”wŒiƒŒƒCƒ„‚Ì•\E— ‰æ–Ê‚É‰æ‘œ‚ğ“Ç‚İ‚Ş
[image storage="CG77_0_1" layer=base page=fore]
[p]
[image storage="CG77_1_1" layer=base page=fore]
[p]
[image storage="CG77_2_1" layer=base page=fore]
[p]
[image storage="CG77_3_1" layer=base page=fore]
[p]
[image storage="CG77_0_2" layer=base page=fore]
[p]
[image storage="CG77_3_2" layer=base page=fore]
[p]
[image storage="CG77_4_1" layer=base page=fore]
[p]
[wait time=300 mode="normal" canskip=false]
[jump storage="album.ks" target=*album_loop0]

*078|
[rclick jump=true target="*album_menu" storage="album.ks" enabled=true]
[eval exp="sf.showpagebreak = 0"]
[er]
[layopt layer=massage0 page=back visible=false]
;”wŒiƒŒƒCƒ„‚Ì•\E— ‰æ–Ê‚É‰æ‘œ‚ğ“Ç‚İ‚Ş
[image storage="CG78_0_1" layer=base page=fore]
[p]
[image storage="CG78_1_1" layer=base page=fore]
[p]
[image storage="CG78_1_2" layer=base page=fore]
[p]
[image storage="CG78_2_1" layer=base page=fore]
[p]
[image storage="CG78_3_1" layer=base page=fore]
[p]
[image storage="CG78_4_1" layer=base page=fore]
[p]
[image storage="CG78_3_2" layer=base page=fore]
[p]
[image storage="CG78_4_2" layer=base page=fore]
[p]
[wait time=300 mode="normal" canskip=false]
[jump storage="album.ks" target=*album_loop0]

*079|
[rclick jump=true target="*album_menu" storage="album.ks" enabled=true]
[eval exp="sf.showpagebreak = 0"]
[er]
[layopt layer=massage0 page=back visible=false]
;”wŒiƒŒƒCƒ„‚Ì•\E— ‰æ–Ê‚É‰æ‘œ‚ğ“Ç‚İ‚Ş
[image storage="CG79_0_1" layer=base page=fore]
[p]
[image storage="CG79_1_1" layer=base page=fore]
[p]
[image storage="CG79_2_1" layer=base page=fore]
[p]
[image storage="CG79_3_1" layer=base page=fore]
[p]
[image storage="CG79_4_1" layer=base page=fore]
[p]
[image storage="CG79_5_1" layer=base page=fore]
[p]
[image storage="CG79_5_2" layer=base page=fore]
[p]
[image storage="CG79_6_1" layer=base page=fore]
[p]
[image storage="CG79_6_2" layer=base page=fore]
[p]
[wait time=300 mode="normal" canskip=false]
[jump storage="album.ks" target=*album_loop0]

*080|
[rclick jump=true target="*album_menu" storage="album.ks" enabled=true]
[eval exp="sf.showpagebreak = 0"]
[er]
[layopt layer=massage0 page=back visible=false]
;”wŒiƒŒƒCƒ„‚Ì•\E— ‰æ–Ê‚É‰æ‘œ‚ğ“Ç‚İ‚Ş
[image storage="CG80_0_1" layer=base page=fore]
[p]
[image storage="CG80_1_1" layer=base page=fore]
[p]
[image storage="CG80_2_1" layer=base page=fore]
[p]
[image storage="CG80_3_1" layer=base page=fore]
[p]
[image storage="CG80_4_1" layer=base page=fore]
[p]
[image storage="CG80_5_1" layer=base page=fore]
[p]
[image storage="CG80_4_2" layer=base page=fore]
[p]
[image storage="CG80_5_2" layer=base page=fore]
[p]
[wait time=300 mode="normal" canskip=false]
[jump storage="album.ks" target=*album_loop0]

;
; u–ß‚év‚ª‘I‘ğ‚³‚ê‚½
;
*album_return
; ƒ}ƒEƒX‰EƒNƒŠƒbƒN‚³‚ê‚½‚Æ‚«‚Ì“®ì‚ğŒ³‚É–ß‚·
;[call storage="album.ks" target=*album_menu]
; ƒƒ‚ƒŠã‚Ìx‚O‚ğ“Ç‚İ‚İAó‘Ô•œ‹A
[tempload place=6 bgm=false]
; ƒ}ƒEƒX‰EƒNƒŠƒbƒN‚³‚ê‚½‚Æ‚«‚Ì“®ì‚ğŒ³‚É–ß‚·
[rclick call=false jump=false]
[jump storage="album.ks" target=*album_loop0]

; ‰EƒNƒŠƒbƒNƒTƒuƒ‹[ƒ`ƒ“‚ÌI—¹
[return]