//
// 確認ダイアログボックスの各種パラメータを設定する
//
function YesNoDialogWindow_config()
{

// ☆ここから…

;dialogImage = "dialog_base.png";			// ダイアログボックス本体の画像ファイル

;dialogYesButtonImage = "dialog_bt_yes.png";// ［はい］ボタンの画像ファイル
;dialogYesButtonLeft = 54;					// 同、Ｘ座標（ピクセル）
;dialogYesButtonTop = 100;					// 同、Ｙ座標（ピクセル）

;dialogNoButtonImage = "dialog_bt_no.png";	// ［いいえ］ボタンの画像ファイル
;dialogNoButtonLeft = 54;					// 同、Ｘ座標（ピクセル）
;dialogNoButtonTop = 156;					// 同、Ｙ座標（ピクセル）

;dialogFontHeight = 18;						// メッセージのフォント高さ（ピクセル）
;dialogFontFace = "haikarapop";		// メッセージのフォント
;dialogFontBold = false;					// メッセージを太字にする場合はtrue
;dialogFontColor = 0xffffff;				// メッセージの色（0xRRGGBB形式/色定数）
;dialogShadowLevel = 0;						// 影の不透明度（0:影なし）
;dialogShadowColor = 0x000000;				// 影の色（0xRRGGBB形式/色定数）
;dialogShadowWidth = 0;						// 影の幅（0:シャープ～ぼける）
;dialogShadowOffsetX = 0;					// 影の位置のＸ座標（0:真下）
;dialogShadowOffsetY = 0;					// 同、Ｙ座標（0:真下）

;dialogMessageLeft = 11;					// メッセージ描画領域の左上隅Ｘ座標（ピクセル）
;dialogMessageTop = 60;						// 同、Ｙ座標（ピクセル）
;dialogMessageWidth = 314 - 37*2;			// メッセージ描画領域の最大横幅（ピクセル）
;dialogMessageHeight = 185 - 63 - 75;		// 同、高さ（ピクセル）

;dialogCaptionFontHeight = 18;				// タイトルバーキャプションのフォント高さ（ピクセル）
;dialogCaptionTop = 18;						// 同、Ｙ座標（ピクセル）

// ☆ここまでの間のパラメータを修正してください

}

