// スクロールバーに付随する各種ボタンのベースになるクラス
class ScrollBarButtonBaseLayer extends ButtonLayer
{
	// コンストラクタ
	function ScrollBarButtonBaseLayer(window, parent)
	{
		super.ButtonLayer(window, parent);
		focusable = false;
	}

	// デストラクタ
	function finalize()
	{
		super.finalize();
	}

	// 状態 s に対応する画像を描画するメソッド（オーバーライド）
	function drawState(s)
	{
		// s :  0 : 普通の状態
		//      1 : ボタンが押された状態
		//      2 : ボタンの上にマウスカーソルがある状態
		if(!enabled)
		{
			s = 0; // 無効状態
		}

		if(Butt_imageLoaded)
		{
			// ボタンイメージが読み込まれている
			// TODO: keyboard focus
			imageLeft = -s * width;
		}
		else
		{
			if(Butt_keyPressed) s = 1; // 押されている

			// 枠とキャプションを描画
			// クリア
			face = dfAlpha;
			colorRect(0, 0, width, height, 0, -255);
			// 下地を塗る
			if(Butt_color != clNone)
				colorRect(0, 0, width, height, Butt_color);
			// 文字のサイズを得る
			var tw, th;
			tw = font.getTextWidth(Butt_caption);
			th = font.getTextHeight(Butt_caption);
			var r = (Butt_color >> 16) & 0xFF;
			var g = (Butt_color >> 8) & 0xFF;
			var b = Butt_color & 0xFF;
			var _r, _g, _b;
			_r = r < 127 ? r + 128 : 255;
			_g = g < 127 ? g + 128 : 255;
			_b = b < 127 ? b + 128 : 255;
			var bright = (_r << 16) | (_g << 8) | _b;
			_r = r > 128 ? r - 128 : 0;
			_g = g > 128 ? g - 128 : 0;
			_b = b > 128 ? b - 128 : 0;
			var dark = (_r << 16) | (_g << 8) | _b;
			if(s == 0 || s == 2)
			{
				// 通常あるいはマウスが上にある
				colorRect(0, 0, width, 1, bright);
				colorRect(0, 1, 1, height-2, bright);
				colorRect(width-1, 1, 1, height-1, dark);
				colorRect(1, height-1, width-2, 1, dark);
				drawText((width-tw)>>1, (height-th)>>1, 
					Butt_caption, Butt_captionColor, nodeEnabled?255:128);
			}
			else
			{
				// 押されている
				colorRect(0, 0, width, 1, dark);
				colorRect(0, 1, 1, height-2, dark);
				colorRect(width-1, 1, 1, height-1, bright);
				colorRect(1, height-1, width-2, 1, bright);
				drawText(((width-tw)>>1) +1, ((height-th)>>1) +1, 
					Butt_caption, Butt_captionColor, nodeEnabled?255:128);
			}

			if(s != 0)
				colorRect(2, 2, width-4, height-4, clHighlight, 64); // ハイライトする
		}
	}
}

// スクロールバーの上下(左右)のボタン用のクラス
class GraphicalScrollBarButtonLayer extends ButtonLayer
{
	var onClickFunction;
	var timer;

	// コンストラクタ
	function GraphicalScrollBarButtonLayer(window, parent, func, storage, key)
	{
		super.ButtonLayer(window, parent);
		focusable = false;
		visible = true;
		onClickFunction = func;

		loadImages(storage, key);

		timer = new Timer(onTimer, "");
		timer.capacity = 1;
	}

	// デストラクタ
	function finalize()
	{
		invalidate timer;
		super.finalize();
	}

	// 以下３つはマウス系イベントハンドラ（いずれもオーバーライド）
	function onMouseDown(x, y, button, shift)
	{
		if(enabled && button == mbLeft)
		{
			onClickFunction(this);
			timer.interval = 700;
			timer.enabled = true;
		}
		super.onMouseDown(...);
	}

	function onMouseUp(x, y, button, shift)
	{
		timer.enabled = false;
		super.onMouseUp(...);
	}

	function onMouseLeave()
	{
		timer.enabled = false;
		super.onMouseLeave(...);
	}

	// タイマーから呼び出されるメソッド
	function onTimer()
	{
		if(this isvalid)
		{
			onClickFunction(this);
			timer.interval = 50;
		}
	}
}

// スクロールバー背景用のクラス
class GraphicalScrollBarBaseLayer extends GraphicalScrollBarButtonLayer
{
	var mask; // 背景画像のクリック可能領域を表す画像
	var func; // onClickFunction を間に挟むための参照

	// コンストラクタ
	function GraphicalScrollBarBaseLayer(window, parent, func, storage, key, maskstorage)
	{
		super.GraphicalScrollBarButtonLayer(window, parent, onClickFunction, storage, key);
		this.func = func;
		if(maskstorage != "")
		{
			mask = new global.Layer(window, this);
			mask.loadImages(maskstorage);
		}
	}

	// デストラクタ
	function finalize()
	{
		invalidate mask if mask !== void;
		super.finalize();
	}

	// マウスカーソルが有効な領域内にあるかどうかをチェックするため drawState メソッドをオーバーライド
	function drawState(s)
	{
		super.drawState(mask === void || cursorX < 0 || cursorX >= mask.imageWidth || cursorY < 0 || cursorY >= mask.imageHeight || mask.getMainPixel(cursorX, cursorY) ? s : 0);
	}

	// マウスカーソルが有効な領域内にあるかどうかをチェックするため onMouseMove メソッドをオーバーライド
	function onMouseMove(x, y, shift)
	{
		super.onMouseMove(...);
		if(mask !== void)
			drawState(mask.getMainPixel(x, y) ? 2 : 0);
	}

	// クリックされた位置が有効な領域の場合のみ func を呼び出すためのメソッド
	function onClickFunction(obj)
	{
		if(mask === void || mask.getMainPixel(cursorX, cursorY))
			func(this);
	}
}

// スライダー(ドラッグして動かせる部分)用のクラス
class GraphicalScrollBarSliderLayer extends ButtonLayer
{
	var uImage, mImage, lImage;
	var uKey, mKey, lKey;
	var _minPos = 0, _maxPos = 100;
	var offset;
	var onMove;
	var onMoveCompleted;

	// コンストラクタ
	function GraphicalScrollBarSliderLayer(window, parent, movefunc, movecompfunc, uImage, uKey, mImage, mKey, lImage, lKey)
	{
		super.ButtonLayer(window, parent);
		focusable = false;
		visible = true;
		cursor = crDefault;
		onMove = movefunc;
		onMoveCompleted = movecompfunc;
		this.uImage = uImage;
		this.uKey = uKey;
		this.mImage = mImage;
		this.mKey = mKey;
		this.lImage = lImage;
		this.lKey = lKey;
	}

	// デストラクタ
	function finalize()
	{
		super.finalize();
	}

	// 現在位置を取得するメソッド
	function getPos()
	{
		var _maxPos = this._maxPos - length;
		var pos = parentCursorPos - offset;
		if(pos < _minPos)
			pos = _minPos;
		else if(pos > _maxPos)
			pos = _maxPos;
		return pos;
	}

	// 値が変わった時に呼び出されるメソッド
	function onValueChanged(ratio)
	{
		var _maxPos = this._maxPos - length;
		set(_minPos + int((_maxPos - _minPos) * ratio));
	}

	// 以下３つはマウス系イベントハンドラ（いずれもオーバーライド）
	function onMouseDown(x, y, button, shift)
	{
		super.onMouseDown(...);
		offset = parentCursorPos - get();
	}

	function onMouseMove(x, y, shift)
	{
		super.onMouseMove(...);
		if(Butt_mouseDown)
		{
			var pos = getPos();
			onMove(this, (pos - _minPos) / (_maxPos - length - _minPos));
			set(pos);
		}
	}

	function onMouseUp(x, y, button, shift)
	{
		if(enabled && button == mbLeft)
			onMoveCompleted(this, (getPos() - _minPos) / (_maxPos - length - _minPos));
		super.onMouseUp(...);
	}

	// 最小値の時の位置を設定／取得するプロパティ
	property minPos
	{
		setter(pos)
		{
			_minPos = pos;
		}
		getter()
		{
			return _minPos;
		}
	}

	// 最大値の時の位置を設定／取得するプロパティ
	property maxPos
	{
		setter(pos)
		{
			_maxPos = pos;
		}
		getter()
		{
			return _maxPos;
		}
	}
}

// 水平スライダー用のクラス
class HorizontalGraphicalScrollBarSliderLayer extends GraphicalScrollBarSliderLayer
{
	// コンストラクタ
	function HorizontalGraphicalScrollBarSliderLayer(window, parent, movefunc, movecompfunc, uImage, uKey, mImage, mKey, lImage, lKey)
	{
		super.GraphicalScrollBarSliderLayer(...);
	}

	// デストラクタ
	function finalize()
	{
		super.finalize();
	}

	// 位置を設定するメソッド
	function set(pos)
	{
		left = pos;
	}

	// 現在位置を返すメソッド
	function get()
	{
		return left;
	}

	// トラックバーの長さ(幅)を設定するメソッド
	function setWidth(width)
	{
		if(uImage === void || mImage === void || lImage === void)
		{
			this.width = width;
			return;
		}
		var rLayer = new global.Layer(window, this);
		var cLayer = new global.Layer(window, this);
		var lLayer = new global.Layer(window, this);
		rLayer.loadImages(uImage, uKey);
		cLayer.loadImages(mImage, mKey);
		lLayer.loadImages(lImage, lKey);
		rLayer.setSize(rLayer.imageWidth \ 3, rLayer.imageHeight);
		cLayer.setSize(cLayer.imageWidth \ 3, cLayer.imageHeight);
		lLayer.setSize(lLayer.imageWidth \ 3, lLayer.imageHeight);
		var rLen = rLayer.width;
		var lLen = lLayer.width;
		var cLen = width - rLen - lLen;
		global.Layer.setImageSize(width * 3, rLayer.height < cLayer.height ? (rLayer.height < lLayer.height ? rLayer.height : lLayer.height) : (cLayer.height < lLayer.height ? cLayer.height : lLayer.height));
		global.Layer.setSize(width, imageHeight);
		global.Layer.setPos(left, (parent.height - height) \ 2);
		var l = 0;
		for(var i=0;i<3;i++)
		{
			copyRect(l, 0, lLayer, lLayer.width * i, 0, lLen, imageHeight);
			l += lLen;
			var c = cLen;
			while(c > 0)
			{
				var w = c > cLayer.width ? cLayer.width : c;
				copyRect(l, 0, cLayer, cLayer.width * i, 0, w, imageHeight);
				l += w;
				c -= w;
			}
			copyRect(l, 0, rLayer, rLayer.width * i, 0, rLen, imageHeight);
			l += rLen;
		}
		invalidate rLayer;
		invalidate cLayer;
		invalidate lLayer;
		callOnPaint = true;
		Butt_imageLoaded = true;
	}

	// 値が変わった時に呼び出されるメソッド
	function onValueChanged(ratio)
	{
		var _maxPos = this._maxPos - length;
		set(_minPos + int((_maxPos - _minPos) * (1. - ratio)));
	}

	// 親レイヤでのマウスカーソルの位置（x座標）を取得するプロパティ
	property parentCursorPos
	{
		getter()
		{
			return parent.cursorX;
		}
	}

	// トラックバーの長さを設定／取得するプロパティ
	property length
	{
		setter(l)
		{
			setWidth(l);
		}
		getter()
		{
			return width;
		}
	}
}

// 垂直スライダー用のクラス
class VerticalGraphicalScrollBarSliderLayer extends GraphicalScrollBarSliderLayer
{
	// コンストラクタ
	function VerticalGraphicalScrollBarSliderLayer(window, parent, movefunc, movecompfunc, uImage, uKey, mImage, mKey, lImage, lKey)
	{
		super.GraphicalScrollBarSliderLayer(...);
	}

	// デストラクタ
	function finalize()
	{
		super.finalize();
	}

	// 位置を設定するメソッド
	function set(pos)
	{
		top = pos;
	}

	// 現在位置を返すメソッド
	function get()
	{
		return top;
	}

	// トラックバーの長さ(高さ)を設定するメソッド
	function setHeight(height)
	{
		if(uImage === void || mImage === void || lImage === void)
		{
			this.height = height;
			return;
		}
		var tLayer = new global.Layer(window, this);
		var cLayer = new global.Layer(window, this);
		var bLayer = new global.Layer(window, this);
		tLayer.loadImages(uImage, uKey);
		cLayer.loadImages(mImage, mKey);
		bLayer.loadImages(lImage, lKey);
		var tLen = tLayer.height;
		var bLen = bLayer.height;
		var cLen = height - tLen - bLen;
		global.Layer.setImageSize(tLayer.imageWidth < cLayer.imageWidth ? (tLayer.imageWidth < bLayer.imageWidth ? tLayer.imageWidth : bLayer.imageWidth) : (cLayer.imageWidth < bLayer.imageWidth ? cLayer.imageWidth : bLayer.imageWidth), height);
		global.Layer.setSize(imageWidth \ 3, imageHeight);
		global.Layer.setPos((parent.width - width) \ 2, top);
		copyRect(0, 0, tLayer, 0, 0, imageWidth, tLen);
		var t = tLen;
		while(cLen > 0)
		{
			var h = cLen > cLayer.height ? cLayer.height : cLen;
			copyRect(0, t, cLayer, 0, 0, imageWidth, h);
			t += h;
			cLen -= h;
		}
		copyRect(0, t, bLayer, 0, 0, imageWidth, bLen);
		invalidate tLayer;
		invalidate cLayer;
		invalidate bLayer;
		callOnPaint = true;
		Butt_imageLoaded = true;
	}

	// 親レイヤでのマウスカーソルの位置（y座標）を取得するプロパティ
	property parentCursorPos
	{
		getter()
		{
			return parent.cursorY;
		}
	}

	property length
	{
		setter(l)
		{
			setHeight(l);
		}
		getter()
		{
			return height;
		}
	}
}

// スクロールバークラス
class GraphicalScrollBar
{
	var base;
	var incButton, decButton;
	var slider;
	var _minVal = 0, _maxVal = 100, _value = 0;
	var _unitIncrement = 1, _blockIncrement = 10;
	var _visibleAmount;
	var minVisibleAmount = 16;
	var onValueChangedFunction;

	// コンストラクタ
	function GraphicalScrollBar(window, parent, func, settings)
	{
		onValueChangedFunction = func;
		base = new GraphicalScrollBarBaseLayer(window, parent, onBaseClick, settings.base, settings.baseKey, settings.baseMask);
		base.cursor = crDefault;
		incButton = new GraphicalScrollBarButtonLayer(window, base, onIncrement, settings.downButton, settings.downButtonKey);
		decButton = new GraphicalScrollBarButtonLayer(window, base, onDecrement, settings.upButton, settings.upButtonKey);
		base.hitThreshold = settings.baseRectHit < 0 ? -settings.baseRectHit : (settings.baseRectHit ? 0 : 64);
		incButton.hitThreshold = settings.downRectHit < 0 ? -settings.downRectHit : (settings.downRectHit ? 0 : 64);
		decButton.hitThreshold = settings.upRectHit < 0 ? -settings.upRectHit : (settings.upRectHit ? 0 : 64);
	}

	// デストラクタ
	function finalize()
	{
		invalidate slider if slider !== void;
		invalidate decButton;
		invalidate incButton;
		invalidate base;
	}

	// 位置を設定するメソッド
	function setPos(x, y)
	{
		base.setPos(x, y);
	}

	// ベースレイヤがクリックされた時に呼び出されるメソッド
	function onBaseClick(obj)
	{
		var c = cursorPos;
		var s = sliderPos;
		if(c < s)
			value -= _blockIncrement;
		else if(c > s + sliderLength)
			value += _blockIncrement;
	}

	// 値を増やすボタン（≪ or ▼）が押された時に呼び出されるメソッド
	function onIncrement(obj)
	{
		value += _unitIncrement;
	}

	// 値を減らすボタン（≫ or ▲）が押された時に呼び出されるメソッド
	function onDecrement(obj)
	{
		value -= _unitIncrement;
	}

	// スライダーがドラッグされた時に呼び出されるメソッド
	function onSliderMoved(obj, ratio)
	{
		value = _minVal + int((_maxVal - _minVal + 1) * ratio + .5);
	}

	// スライダーのドラッグが終わった時に呼び出されるメソッド
	function onSliderMoveCompleted(obj, ratio)
	{
		onSliderMoved(...);
	}

	// 値が変わった時に呼び出されるメソッド
	function onValueChanged(notify = true)
	{
		if(slider !== void)
			slider.onValueChanged((_value - _minVal) / (_maxVal - _minVal));
		if(notify)
			onValueChangedFunction(value);
	}

	// 最小値を設定／取得するプロパティ
	property minVal
	{
		setter(val)
		{
			_minVal = val;
			if(_minVal >= _maxVal)
				_maxVal = _minVal + 1;
			if(_value < _minVal)
				_value = _minVal;
			onValueChanged(false);
		}
		getter()
		{
			return _minVal;
		}
	}

	// 最大値を設定／取得するプロパティ
	property maxVal
	{
		setter(val)
		{
			_maxVal = val;
			if(_maxVal <= _minVal)
				_minVal = _maxVal - 1;
			if(_value > _maxVal)
				_value = _maxVal;
			onValueChanged(false);
		}
		getter()
		{
			return _maxVal;
		}
	}

	// ボタンを押した時に増減する値を設定／取得するプロパティ
	property unitIncrement
	{
		setter(val)
		{
			_unitIncrement = val;
		}
		getter()
		{
			return _unitIncrement;
		}
	}

	// ベースレイヤをクリックした時に増減する値を設定／取得するプロパティ
	property blockIncrement
	{
		setter(val)
		{
			_blockIncrement = val;
		}
		getter()
		{
			return _blockIncrement;
		}
	}

	// スライダーの長さを設定／取得するプロパティ
	property visibleAmount
	{
		setter(val)
		{
			if(slider !== void)
			{
				_visibleAmount = val;
				var maxLength = slider.maxPos - slider.minPos;
				if(_visibleAmount >= maxLength)
					_visibleAmount = maxLength - 1;
				if(_visibleAmount < minVisibleAmount)
					_visibleAmount = minVisibleAmount;
				sliderLength = _visibleAmount;
				onValueChanged(false);
			}
		}
		getter()
		{
			return _visibleAmount;
		}
	}

	// スクロールバーの長さに対するスライダーの長さの比を設定／取得するプロパティ
	property visibleAmountRatio
	{
		setter(val)
		{
			visibleAmount = int((slider.maxPos - slider.minPos) * val);
		}
		getter()
		{
			return visibleAmount / (slider.maxPos - slider.minPos);
		}
	}

	// 値を設定／取得するプロパティ
	property value
	{
		setter(val)
		{
			_value = val;
			if(_value < _minVal)
				_value = _minVal;
			else if(_value > _maxVal)
				_value = _maxVal;
			onValueChanged();
		}
		getter()
		{
			return _value;
		}
	}

	// 使用可／不可を設定／取得するプロパティ
	property enabled
	{
		setter(e)
		{
			base.enabled = e;
		}
		getter()
		{
			return base.enabled;
		}
	}

	// 可視／不可視を設定／取得するプロパティ
	property visible
	{
		setter(v)
		{
			base.visible = v;
		}
		getter()
		{
			return base.visible;
		}
	}

	// 左端の位置を設定／取得するプロパティ
	property left
	{
		setter(val)
		{
			setPos(val, top);
		}
		getter()
		{
			return base.left;
		}
	}

	// 上端の位置を設定／取得するプロパティ
	property top
	{
		setter(val)
		{
			setPos(left, val);
		}
		getter()
		{
			return base.top;
		}
	}

	// 重ね合わせ順序を設定／取得するプロパティ
	property absolute
	{
		setter(val)
		{
			base.absolute = val;
		}
		getter()
		{
			return base.absolute;
		}
	}

	// 不透明度を設定／取得するプロパティ
	property opacity
	{
		setter(val)
		{
			base.opacity = val;
		}
		getter()
		{
			return base.opacity;
		}
	}

	// スライダーの長さを設定／取得するプロパティ
	property sliderLength
	{
		setter(length)
		{
			slider.length = length;
		}
		getter()
		{
			return slider.length;
		}
	}
}

// 水平スクロールバークラス
class HorizontalGraphicalScrollBar extends GraphicalScrollBar
{
	// コンストラクタ
	function HorizontalGraphicalScrollBar(window, parent, func, settings)
	{
		super.GraphicalScrollBar(...);

		incButton.setPos(0, (base.height - incButton.height) \ 2);
		decButton.setPos(base.width - decButton.width, (base.height - decButton.height) \ 2);

		slider = new HorizontalGraphicalScrollBarSliderLayer(
			window, base,
			onSliderMoved, onSliderMoveCompleted,
			settings.sliderTop, settings.sliderTopKey,
			settings.sliderMiddle, settings.sliderMiddleKey,
			settings.sliderBottom, settings.sliderBottomKey);
		slider.minPos = decButton.width;
		slider.maxPos = base.width - incButton.width;
		slider.top = (base.height - slider.height) \ 2;
		slider.hitThreshold = settings.sliderRectHit < 0 ? -settings.sliderRectHit : (settings.sliderRectHit ? 0 : 64);

		var tmp = new Layer(window, base);
		tmp.loadImages(settings.sliderTop);
		minVisibleAmount = tmp.imageWidth;
		tmp.loadImages(settings.sliderBottom);
		minVisibleAmount += tmp.imageWidth;
		invalidate tmp;

		visibleAmount = base.width \ 10;

		onValueChanged(false);
	}

	// デストラクタ
	function finalize()
	{
		super.finalize();
	}

	// ベースレイヤがクリックされた時に呼び出されるメソッド（オーバーライド）
	function onBaseClick(obj)
	{
		var c = cursorPos;
		var s = sliderPos;
		if(c < s)
			value += _blockIncrement;
		else if(c > s + sliderLength)
			value -= _blockIncrement;
		onValueChanged();
	}

	// スライダーがドラッグされた時に呼び出されるメソッド（オーバーライド）
	function onSliderMoved(obj, ratio)
	{
		value = _minVal + int((_maxVal - _minVal + 1) * (1. - ratio) + .5);
	}

	// マウスカーソルの位置を取得するプロパティ
	property cursorPos
	{
		getter()
		{
			return base.cursorX;
		}
	}

	// スライダーの位置を取得するプロパティ
	property sliderPos
	{
		getter()
		{
			return slider.left;
		}
	}
}

// 垂直スクロールバークラス
class VerticalGraphicalScrollBar extends GraphicalScrollBar
{
	// コンストラクタ
	function VerticalGraphicalScrollBar(window, parent, func, settings)
	{
		super.GraphicalScrollBar(...);

		incButton.setPos((base.width - incButton.width) \ 2, base.height - incButton.height);
		decButton.setPos((base.width - decButton.width) \ 2, 0);

		slider = new VerticalGraphicalScrollBarSliderLayer(
			window, base,
			onSliderMoved, onSliderMoveCompleted,
			settings.sliderTop, settings.sliderTopKey,
			settings.sliderMiddle, settings.sliderMiddleKey,
			settings.sliderBottom, settings.sliderBottomKey);
		slider.minPos = decButton.height;
		slider.maxPos = base.height - incButton.height;
		slider.top = (base.width - slider.width) \ 2;
		slider.hitThreshold = settings.sliderRectHit < 0 ? -settings.sliderRectHit : (settings.sliderRectHit ? 0 : 64);

		var tmp = new Layer(window, base);
		tmp.loadImages(settings.sliderTop);
		minVisibleAmount = tmp.imageHeight;
		tmp.loadImages(settings.sliderBottom);
		minVisibleAmount += tmp.imageHeight;
		invalidate tmp;

		visibleAmount = base.height \ 10;

		onValueChanged(false);
	}

	// デストラクタ
	function finalize()
	{
		super.finalize();
	}

	// マウスカーソルの位置を取得するプロパティ
	property cursorPos
	{
		getter()
		{
			return base.cursorY;
		}
	}

	// スライダーの位置を取得するプロパティ
	property sliderPos
	{
		getter()
		{
			return slider.top;
		}
	}
}
