;
; album_init.ks…アルバム画面のパラメータ設定
;

;
; 使い方：
;   [call storage="album_init.ks" target=*album_init]
;
; 注意事項：
;   ‐first.ksの先頭（セーブ可能なラベルより前に）で当サブルーチンを呼び出すこと
;   ‐macro.ksのeventcgマクロを使えば、簡単に配列sf.album_flagのフラグを変更できる
;
; 使用している変数：
;   tf.album_storage   … イベント絵のファイル名の配列
;   tf.album_thumbnail … 同、サムネイル画像のファイル名の配列
;   sf.album_flag      … そのイベント絵を閲覧したか否かの配列。初期値false（各KAGシナリオでこのフラグを変更する）
;

;
; 以下はテスト兼スクリーンショットを取るためのサンプル
;


*album_init
; 配列tf.album_storageがまだ作られていなければ…
[if exp="tf.album_storage === void"]
	; 配列tf.album_storageを作る
	[eval exp="tf.album_storage = []"]
	; 要素0～199にイベント絵のファイル名を代入する
	[eval exp="tf.album_storage[0]  = '*001'"]
	[eval exp="tf.album_storage[1]  = '*002'"]
	[eval exp="tf.album_storage[2]  = '*003'"]
	[eval exp="tf.album_storage[3]  = '*004'"]
	[eval exp="tf.album_storage[4]  = '*005'"]
	[eval exp="tf.album_storage[5]  = '*006'"]
	[eval exp="tf.album_storage[6]  = '*007'"]
	[eval exp="tf.album_storage[7]  = '*008'"]
	[eval exp="tf.album_storage[8]  = '*009'"]
	[eval exp="tf.album_storage[9]  = '*010'"]
	[eval exp="tf.album_storage[10]  = '*011'"]
	[eval exp="tf.album_storage[11]  = '*012'"]
	[eval exp="tf.album_storage[12]  = '*013'"]
	[eval exp="tf.album_storage[13]  = '*014'"]
	[eval exp="tf.album_storage[14]  = '*015'"]
	[eval exp="tf.album_storage[15]  = '*016'"]
	[eval exp="tf.album_storage[16]  = '*017'"]
	[eval exp="tf.album_storage[17]  = '*018'"]
	[eval exp="tf.album_storage[18]  = '*019'"]
	[eval exp="tf.album_storage[19]  = '*020'"]
	[eval exp="tf.album_storage[20]  = '*021'"]
	[eval exp="tf.album_storage[21]  = '*022'"]
	[eval exp="tf.album_storage[22]  = '*023'"]
	[eval exp="tf.album_storage[23]  = '*024'"]
	[eval exp="tf.album_storage[24]  = '*025'"]
	[eval exp="tf.album_storage[25]  = '*026'"]
	[eval exp="tf.album_storage[26]  = '*027'"]
	[eval exp="tf.album_storage[27]  = '*028'"]
	[eval exp="tf.album_storage[28]  = '*029'"]
	[eval exp="tf.album_storage[29]  = '*030'"]
	[eval exp="tf.album_storage[30]  = '*031'"]
	[eval exp="tf.album_storage[31]  = '*032'"]
	[eval exp="tf.album_storage[32]  = '*033'"]
	[eval exp="tf.album_storage[33]  = '*034'"]
	[eval exp="tf.album_storage[34]  = '*035'"]
	[eval exp="tf.album_storage[35]  = '*036'"]
	[eval exp="tf.album_storage[36]  = '*037'"]
	[eval exp="tf.album_storage[37]  = '*038'"]
	[eval exp="tf.album_storage[38]  = '*039'"]
	[eval exp="tf.album_storage[39]  = '*040'"]
	[eval exp="tf.album_storage[40]  = '*041'"]
	[eval exp="tf.album_storage[41]  = '*042'"]
	[eval exp="tf.album_storage[42]  = '*043'"]
	[eval exp="tf.album_storage[43]  = '*044'"]
	[eval exp="tf.album_storage[44]  = '*045'"]
	[eval exp="tf.album_storage[45]  = '*046'"]
	[eval exp="tf.album_storage[46]  = '*047'"]
	[eval exp="tf.album_storage[47]  = '*048'"]
	[eval exp="tf.album_storage[48]  = '*049'"]
	[eval exp="tf.album_storage[49]  = '*050'"]
	[eval exp="tf.album_storage[50]  = '*051'"]
	[eval exp="tf.album_storage[51]  = '*052'"]
	[eval exp="tf.album_storage[52]  = '*053'"]
	[eval exp="tf.album_storage[53]  = '*054'"]
	[eval exp="tf.album_storage[54]  = '*055'"]
	[eval exp="tf.album_storage[55]  = '*056'"]
	[eval exp="tf.album_storage[56]  = '*057'"]
	[eval exp="tf.album_storage[57]  = '*058'"]
	[eval exp="tf.album_storage[58]  = '*059'"]
	[eval exp="tf.album_storage[59]  = '*060'"]
	[eval exp="tf.album_storage[60]  = '*061'"]
	[eval exp="tf.album_storage[61]  = '*062'"]
	[eval exp="tf.album_storage[62]  = '*063'"]
	[eval exp="tf.album_storage[63]  = '*064'"]
	[eval exp="tf.album_storage[64]  = '*065'"]
	[eval exp="tf.album_storage[65]  = '*066'"]
	[eval exp="tf.album_storage[66]  = '*067'"]
	[eval exp="tf.album_storage[67]  = '*068'"]
	[eval exp="tf.album_storage[68]  = '*069'"]
	[eval exp="tf.album_storage[69]  = '*070'"]
	[eval exp="tf.album_storage[70]  = '*071'"]
	[eval exp="tf.album_storage[71]  = '*072'"]
	[eval exp="tf.album_storage[72]  = '*073'"]
	[eval exp="tf.album_storage[73]  = '*074'"]
	[eval exp="tf.album_storage[74]  = '*075'"]
	[eval exp="tf.album_storage[75]  = '*076'"]
	[eval exp="tf.album_storage[76]  = '*077'"]
	[eval exp="tf.album_storage[77]  = '*078'"]
	[eval exp="tf.album_storage[78]  = '*079'"]
	[eval exp="tf.album_storage[79]  = '*080'"]

[endif]

; 配列tf.album_thumbnailがまだ作られていなければ…
[if exp="tf.album_thumbnail === void"]
	; 配列tf.album_targetを作る
	[eval exp="tf.album_thumbnail = []"]
	; 要素0～199にサムネイル画像のファイル名を代入する
	[eval exp="tf.album_thumbnail[0]  = 'cg01_m.png'"]
	[eval exp="tf.album_thumbnail[1]  = 'cg02_m.png'"]
	[eval exp="tf.album_thumbnail[2]  = 'cg03_m.png'"]
	[eval exp="tf.album_thumbnail[3]  = 'cg04_m.png'"]
	[eval exp="tf.album_thumbnail[4]  = 'cg05_m.png'"]
	[eval exp="tf.album_thumbnail[5]  = 'cg06_m.png'"]
	[eval exp="tf.album_thumbnail[6]  = 'cg07_m.png'"]
	[eval exp="tf.album_thumbnail[7]  = 'cg08_m.png'"]
	[eval exp="tf.album_thumbnail[8]  = 'cg09_m.png'"]
	[eval exp="tf.album_thumbnail[9]  = 'cg10_m.png'"]
	[eval exp="tf.album_thumbnail[10]  = 'cg11_m.png'"]
	[eval exp="tf.album_thumbnail[11]  = 'cg12_m.png'"]
	[eval exp="tf.album_thumbnail[12]  = 'cg13_m.png'"]
	[eval exp="tf.album_thumbnail[13]  = 'cg14_m.png'"]
	[eval exp="tf.album_thumbnail[14]  = 'cg15_m.png'"]
	[eval exp="tf.album_thumbnail[15]  = 'cg16_m.png'"]
	[eval exp="tf.album_thumbnail[16]  = 'cg17_m.png'"]
	[eval exp="tf.album_thumbnail[17]  = 'cg18_m.png'"]
	[eval exp="tf.album_thumbnail[18]  = 'cg19_m.png'"]
	[eval exp="tf.album_thumbnail[19]  = 'cg20_m.png'"]
	[eval exp="tf.album_thumbnail[20]  = 'cg21_m.png'"]
	[eval exp="tf.album_thumbnail[21]  = 'cg22_m.png'"]
	[eval exp="tf.album_thumbnail[22]  = 'cg23_m.png'"]
	[eval exp="tf.album_thumbnail[23]  = 'cg24_m.png'"]
	[eval exp="tf.album_thumbnail[24]  = 'cg25_m.png'"]
	[eval exp="tf.album_thumbnail[25]  = 'cg26_m.png'"]
	[eval exp="tf.album_thumbnail[26]  = 'cg27_m.png'"]
	[eval exp="tf.album_thumbnail[27]  = 'cg28_m.png'"]
	[eval exp="tf.album_thumbnail[28]  = 'cg29_m.png'"]
	[eval exp="tf.album_thumbnail[29]  = 'cg30_m.png'"]
	[eval exp="tf.album_thumbnail[30]  = 'cg31_m.png'"]
	[eval exp="tf.album_thumbnail[31]  = 'cg32_m.png'"]
	[eval exp="tf.album_thumbnail[32]  = 'cg33_m.png'"]
	[eval exp="tf.album_thumbnail[33]  = 'cg34_m.png'"]
	[eval exp="tf.album_thumbnail[34]  = 'cg35_m.png'"]
	[eval exp="tf.album_thumbnail[35]  = 'cg36_m.png'"]
	[eval exp="tf.album_thumbnail[36]  = 'cg37_m.png'"]
	[eval exp="tf.album_thumbnail[37]  = 'cg38_m.png'"]
	[eval exp="tf.album_thumbnail[38]  = 'cg39_m.png'"]
	[eval exp="tf.album_thumbnail[39]  = 'cg40_m.png'"]
	[eval exp="tf.album_thumbnail[40]  = 'cg41_m.png'"]
	[eval exp="tf.album_thumbnail[41]  = 'cg42_m.png'"]
	[eval exp="tf.album_thumbnail[42]  = 'cg43_m.png'"]
	[eval exp="tf.album_thumbnail[43]  = 'cg44_m.png'"]
	[eval exp="tf.album_thumbnail[44]  = 'cg45_m.png'"]
	[eval exp="tf.album_thumbnail[45]  = 'cg46_m.png'"]
	[eval exp="tf.album_thumbnail[46]  = 'cg47_m.png'"]
	[eval exp="tf.album_thumbnail[47]  = 'cg48_m.png'"]
	[eval exp="tf.album_thumbnail[48]  = 'cg49_m.png'"]
	[eval exp="tf.album_thumbnail[49]  = 'cg50_m.png'"]
	[eval exp="tf.album_thumbnail[50]  = 'cg51_m.png'"]
	[eval exp="tf.album_thumbnail[51]  = 'cg52_m.png'"]
	[eval exp="tf.album_thumbnail[52]  = 'cg53_m.png'"]
	[eval exp="tf.album_thumbnail[53]  = 'cg54_m.png'"]
	[eval exp="tf.album_thumbnail[54]  = 'cg55_m.png'"]
	[eval exp="tf.album_thumbnail[55]  = 'cg56_m.png'"]
	[eval exp="tf.album_thumbnail[56]  = 'cg57_m.png'"]
	[eval exp="tf.album_thumbnail[57]  = 'cg58_m.png'"]
	[eval exp="tf.album_thumbnail[58]  = 'cg59_m.png'"]
	[eval exp="tf.album_thumbnail[59]  = 'cg60_m.png'"]
	[eval exp="tf.album_thumbnail[60]  = 'cg61_m.png'"]
	[eval exp="tf.album_thumbnail[61]  = 'cg62_m.png'"]
	[eval exp="tf.album_thumbnail[62]  = 'cg63_m.png'"]
	[eval exp="tf.album_thumbnail[63]  = 'cg64_m.png'"]
	[eval exp="tf.album_thumbnail[64]  = 'cg65_m.png'"]
	[eval exp="tf.album_thumbnail[65]  = 'cg66_m.png'"]
	[eval exp="tf.album_thumbnail[66]  = 'cg67_m.png'"]
	[eval exp="tf.album_thumbnail[67]  = 'cg68_m.png'"]
	[eval exp="tf.album_thumbnail[68]  = 'cg69_m.png'"]
	[eval exp="tf.album_thumbnail[69]  = 'cg70_m.png'"]
	[eval exp="tf.album_thumbnail[70]  = 'cg71_m.png'"]
	[eval exp="tf.album_thumbnail[71]  = 'cg72_m.png'"]
	[eval exp="tf.album_thumbnail[72]  = 'cg73_m.png'"]
	[eval exp="tf.album_thumbnail[73]  = 'cg74_m.png'"]
	[eval exp="tf.album_thumbnail[74]  = 'cg75_m.png'"]
	[eval exp="tf.album_thumbnail[75]  = 'cg76_m.png'"]
	[eval exp="tf.album_thumbnail[76]  = 'cg77_m.png'"]
	[eval exp="tf.album_thumbnail[77]  = 'cg78_m.png'"]
	[eval exp="tf.album_thumbnail[78]  = 'cg79_m.png'"]
	[eval exp="tf.album_thumbnail[79]  = 'cg80_m.png'"]
	[eval exp="tf.album_thumbnail[80]  = 'cg81_m.png'"]

[endif]

; 配列sf.album_flagがまだ作られていなければ…
[if exp="sf.album_flag === void"]
	; 配列sf.album_flagを作る
	[eval exp="sf.album_flag = []"]
	; 要素0～199に未見（false）のフラグを代入する。このフラグは各KAGシナリオで閲覧済み（true）に設定する
	[eval exp="sf.album_flag[0]  = false"]
	[eval exp="sf.album_flag[1]  = false"]
	[eval exp="sf.album_flag[2]  = false"]
	[eval exp="sf.album_flag[3]  = false"]
	[eval exp="sf.album_flag[4]  = false"]
	[eval exp="sf.album_flag[5]  = false"]
	[eval exp="sf.album_flag[6]  = false"]
	[eval exp="sf.album_flag[7]  = false"]
	[eval exp="sf.album_flag[8]  = false"]
	[eval exp="sf.album_flag[9]  = false"]
	[eval exp="sf.album_flag[10]  = false"]
	[eval exp="sf.album_flag[11]  = false"]
	[eval exp="sf.album_flag[12]  = false"]
	[eval exp="sf.album_flag[13]  = false"]
	[eval exp="sf.album_flag[14]  = false"]
	[eval exp="sf.album_flag[15]  = false"]
	[eval exp="sf.album_flag[16]  = false"]
	[eval exp="sf.album_flag[17]  = false"]
	[eval exp="sf.album_flag[18]  = false"]
	[eval exp="sf.album_flag[19]  = false"]
	[eval exp="sf.album_flag[20]  = false"]
	[eval exp="sf.album_flag[21]  = false"]
	[eval exp="sf.album_flag[22]  = false"]
	[eval exp="sf.album_flag[23]  = false"]
	[eval exp="sf.album_flag[24]  = false"]
	[eval exp="sf.album_flag[25]  = false"]
	[eval exp="sf.album_flag[26]  = false"]
	[eval exp="sf.album_flag[27]  = false"]
	[eval exp="sf.album_flag[28]  = false"]
	[eval exp="sf.album_flag[29]  = false"]
	[eval exp="sf.album_flag[30]  = false"]
	[eval exp="sf.album_flag[31]  = false"]
	[eval exp="sf.album_flag[32]  = false"]
	[eval exp="sf.album_flag[33]  = false"]
	[eval exp="sf.album_flag[34]  = false"]
	[eval exp="sf.album_flag[35]  = false"]
	[eval exp="sf.album_flag[36]  = false"]
	[eval exp="sf.album_flag[37]  = false"]
	[eval exp="sf.album_flag[38]  = false"]
	[eval exp="sf.album_flag[39]  = false"]
	[eval exp="sf.album_flag[40]  = false"]
	[eval exp="sf.album_flag[41]  = false"]
	[eval exp="sf.album_flag[42]  = false"]
	[eval exp="sf.album_flag[43]  = false"]
	[eval exp="sf.album_flag[44]  = false"]
	[eval exp="sf.album_flag[45]  = false"]
	[eval exp="sf.album_flag[46]  = false"]
	[eval exp="sf.album_flag[47]  = false"]
	[eval exp="sf.album_flag[48]  = false"]
	[eval exp="sf.album_flag[49]  = false"]
	[eval exp="sf.album_flag[50]  = false"]
	[eval exp="sf.album_flag[51]  = false"]
	[eval exp="sf.album_flag[52]  = false"]
	[eval exp="sf.album_flag[53]  = false"]
	[eval exp="sf.album_flag[54]  = false"]
	[eval exp="sf.album_flag[55]  = false"]
	[eval exp="sf.album_flag[56]  = false"]
	[eval exp="sf.album_flag[57]  = false"]
	[eval exp="sf.album_flag[58]  = false"]
	[eval exp="sf.album_flag[59]  = false"]
	[eval exp="sf.album_flag[60]  = false"]
	[eval exp="sf.album_flag[61]  = false"]
	[eval exp="sf.album_flag[62]  = false"]
	[eval exp="sf.album_flag[63]  = false"]
	[eval exp="sf.album_flag[64]  = false"]
	[eval exp="sf.album_flag[65]  = false"]
	[eval exp="sf.album_flag[66]  = false"]
	[eval exp="sf.album_flag[67]  = false"]
	[eval exp="sf.album_flag[68]  = false"]
	[eval exp="sf.album_flag[69]  = false"]
	[eval exp="sf.album_flag[70]  = false"]
	[eval exp="sf.album_flag[71]  = false"]
	[eval exp="sf.album_flag[72]  = false"]
	[eval exp="sf.album_flag[73]  = false"]
	[eval exp="sf.album_flag[74]  = false"]
	[eval exp="sf.album_flag[75]  = false"]
	[eval exp="sf.album_flag[76]  = false"]
	[eval exp="sf.album_flag[77]  = false"]
	[eval exp="sf.album_flag[78]  = false"]
	[eval exp="sf.album_flag[79]  = false"]
	[eval exp="sf.album_flag[80]  = false"]


[endif]


[return]
