KAGLoadScript("SliderLayer2.tjs");
KAGLoadScript("LoadThumbnail.tjs");
KAGLoadScript("SliderFuntion.tjs");
KAGLoadScript("Config_SliderControl.tjs");


// 関数名：
//   marker_on(lay, x, y)
// 機能概要：
//   指定した前景レイヤを指定したＸ、Ｙ座標に表示する
// 引数：
//   lay … 前景レイヤ番号（0, 1, 2…）
//   x   … Ｘ座標（ピクセル）
//   y   … Ｙ座標（ピクセル）
// 戻り値：
//   なし
function marker_on(lay, x, y)
{
	kag.fore.layers[lay].setPos(x, y);
	kag.fore.layers[lay].visible = true;
}

// 関数名：
//   marker_off(lay)
// 機能概要：
//   指定した前景レイヤを非表示にする
// 引数：
//   lay … 前景レイヤ番号（0, 1, 2…）
// 戻り値：
//   なし
function marker_off(lay)
{
	kag.fore.layers[lay].visible = false;
}

// 関数名：
//   get_bookmark_data(num)
// 機能概要：
//   栞の日付とブックマーク名を連結した文字列を返す
// 引数：
//   num … 栞の番号（0, 1, 2…）
// 戻り値：
//   栞がある場合…"[num] YYYY/MM/DD hh:mm ブックマーク名"形式の文字列で返す
//   栞がない場合…"[num] ----/--/-- --:-- (未設定)"という文字列を返す
function get_bookmark_data(num)
{
	var date = kag.getBookMarkDate(num);
	if (date == "")
		return "";
	else
		return "";
}

//-----------------------------
kag.getCurrentRead__org = kag.getCurrentRead;
kag.getCurrentRead = function()
{
// trueならすべてスキップ
if(sf.chSkipAll && kag.skipMode == 3) return true;

return kag.getCurrentRead__org();

} incontextof kag;

//-----------------------------

// 未読もスキップするか否かのフラグ（システム変数）
if (sf.allskip === void)
  sf.allskip = false;  // 初回起動時にはfalseを代入しておく

// ［システム‐未読もスキップ］メニューハンドラの定義
kag.onAllSkipClick = function(sender)
{
  sf.allskip = !sf.allskip;
  allSkipMenuItem.checked = sf.allskip;
  if (sf.allskip)
    skipToNextStopMenuItem.caption = "次の選択肢まで進む(&F)";
  else
    skipToNextStopMenuItem.caption = autoRecordPageShowing ? "次の選択肢/未読まで進む(&F)" : "次の選択肢まで進む(&F)";
} incontextof kag;

// ［未読もスキップ］メニューアイテムを作成
kag.allSkipMenuItem = new KAGMenuItem(kag, "未読もスキップ(&L)", 0, kag.onAllSkipClick, false);
kag.allSkipMenuItem.checked = sf.allskip;

// ［システム］メニューに［未読もスキップ］メニューアイテムを登録
kag.systemMenu.insert(kag.allSkipMenuItem, 3);

// kag.getCurrentRead()メソッドを差し換える
kag.getCurrentRead_org = kag.getCurrentRead;
kag.getCurrentRead = function()
{
  if (sf.allskip)                 // 未読もスキップするなら全て既読
    return true;
  else
    return getCurrentRead_org();  // そうでなければ旧kag.getCurrentRead()メソッドの戻り値を使う
} incontextof kag;



kag.onConductorLabel=function(label,page)
{
// コンダクタがラベルを通過した
if(!usingExtraConductor)
{
incRecordLabel(true);
setRecordLabel(conductor.curStorage, label);
}
setUserSpeed();
if(!usingExtraConductor)
{
if(!getCurrentRead() && skipMode != 4)
{
cancelSkip(); // 未読なのでスキップを停止
nextSkipEnabled=false; //「次選択肢」を禁止
}
else if(f.nextSkipStatus==true)nextSkipEnabled=true; //「nextskip」がtrueの時「次選択肢」を許可
currentLabel = label;
}
if(page !== void && page !== '')
{
if(page[0] == '&') page = (page.substring(1))!;
currentPageName = page;
}
if(page !== void)
{
pushHistoryOfStore();
stablePosibility = false;
dm(conductor.curStorage + " : ラベル/ページ : " + label + "/" + currentPageName);
if(usingExtraConductor) throw new Exception("右クリックサブルーチン内/extraCondutor"
"サブルーチン内では保存可能なラベルを記述できません");
storeFlags(), storeLabelPassed = true, setMenuAccessibleAll();
if(recordHistoryOfStore == 1) // 1 : 保存可能なラベルごと
setToRecordHistory();
}
return true;
};
f.nextSkipStatus=true;

// 履歴にだけ表示拡張タグ
kag.tagHandlers.htext =
function(elm){
if(historyWriteEnabled)
historyLayer.store(elm.text);
return 0;
} incontextof kag;


//return tagHandlers.cm_org(elm); だとなぜかエラーが出るので 
//return tagHandlers.org_cm(elm); に名前を変更
//コメントをつけまくって、逆に見づらい

with(kag) 
{
	.currentMessage = ""; //見出しへの追加文字（メッセージレイヤの一番上に表示されている文字） 
	.storeCurrentMessages = 30; //見出しに追加する文字数 

	//kag.tagHandlersにタグの実装が入っている（[macro][if]等の例外有）
	.tagHandlers.org_ch = .tagHandlers.ch; 
	.tagHandlers.ch = function( elm ) 
	{ 
		// 文字表示 actualChSpeed = chSpeed 実際の文字表示スピード
		var acs = actualChSpeed; 
		//updateBeforeCh 文字を描画する前にいったん画面描画に入るかどうかのカウント
		if(updateBeforeCh) 
		{ 
			if(acs) { updateBeforeCh--; return -5; } else { updateBeforeCh--; } 
		} 
		//上の処理は良く分からないけれど、本来のchタグの先頭部分
		var len = currentMessage.length; 
		//追加文字数がstoreCurrentMessages（ここでは20）以下
		//でかつf.noStoreCurrentMessageがfalseなら文字追加
		if((len < storeCurrentMessages) && (!f.noStoreCurrentMessage)) 
			//substring(<開始文字位置>,<文字数>) 
			//例：var ss="abcdefghijkl".substring(3,3); ss には "def" が代入される
			currentMessage += elm.text.substring(0, storeCurrentMessages - len);
		//追加文字数がstoreCurrentMessagesの時
		//でかつf.noStoreCurrentMessageがfalseなら"……"追加
		if((len == storeCurrentMessages) && (!f.noStoreCurrentMessage))
			currentMessage += "";
		return tagHandlers.org_ch(elm); //本来のchタグの処理に戻る
	} incontextof kag; 

	.tagHandlers.org_cm = .tagHandlers.cm; 
	.tagHandlers.cm = function( elm ) 
	{ 
		currentMessage = ""; // 見出しへの追加文字をリセット 
		return tagHandlers.org_cm(elm); //本来のcmタグの処理に戻る
	} incontextof kag; 

	.saveBookMarkToFile_org = .saveBookMarkToFile; 
	.saveBookMarkToFile = function(fn, savehist = true) 
	{ 
		//readOnlyMode 読み込み専用モードなら、リターン
		if(readOnlyMode) return false; 
		//pcflags「保存可能なラベル」を通過した時点でのフラグ(コア)
		pcflags.currentMessage = currentMessage; // 見出しへの追加文字を栞に保存 
		return saveBookMarkToFile_org(fn, savehist); 
	} incontextof kag; 

	.saveBookMarkWithAsk = function(num) 
	{ 
		// 栞番号 num に栞を設定する 
		// そのとき、設定するかどうかをたずねる 
		if(readOnlyMode) return false; 
		//bookMarkProtectedStates 栞が保護されているかの情報
		if(bookMarkProtectedStates[num]) return false; 
		var prompt = ""; 
//		if(num < numBookMarks) prompt += (num + 1); 
		if(bookMarkDates[num] != "") // bookMarkDates が空文字の場合は栞は存在しない 
			prompt += "データを上書きしますか？"; 
		else
		if(f.noStoreCurrentMessage)
			prompt += "データをセーブしますか？"; 
		else
			prompt += "データをセーブしますか？"; 
		//セーブタイトルを（見出し＋メッセージレイヤの一番上に表示されている文字）にしたいなら
		//上のif(f.noStoreCurrentMessage)からコメントアウトして下のコメントアウトを外してください。
//		prompt += "に「"+ pcflags.currentPageName + " " + currentMessage + "」をはさみますか?"; 
		var result = askYesNo(prompt); 
		//「はい」なら保存
		if(result) return saveBookMark(num); //本来の処理には戻らない
		//「いいえ」ならfalseを返す
		return false; 
	} incontextof kag; 

	.getBookMarkInfoFromData = function(dic, num) 
	{
		// 辞書配列 dic から栞のページ名と日付を読み出し、 
		// bookMarkDates[num] や bookMarkNames[num] に設定する 
		// numBookMarks メニューに用意する栞のサブメニュー項目の数
		if(num < numBookMarks) 
		{ 
			//if(f.noStoreCurrentMessage)
			//	bookMarkNames[num] = dic.currentPageName;
			//else
			//	bookMarkNames[num] = currentMessage; 
			//セーブタイトルを（見出し＋メッセージレイヤの一番上に表示されている文字）にしたいなら
			//上のif(f.noStoreCurrentMessage)からコメントアウトして下のコメントアウトを外してください。
			bookMarkNames[num] = "" + currentMessage;

			var date = new Date(); 
			date.setTime(dic.storeTime); 
			date = "%04d.%02d.%02d %02d:%02d".sprintf( 
			date.getYear(), date.getMonth() + 1, date.getDate(), 
			date.getHours(), date.getMinutes() ); 
			bookMarkDates[num] = date; 
			setBookMarkMenuCaptions(); 
			saveSystemVariables(); 
		} 
	} incontextof kag; 
}
// 最後に通過した[cm]タグから、kag.storeCurrentMessages文字分だけを見出しへの追加文字とする 
// ただし、f.noStoreCurrentMessageが真の間に表示した分は除外 
// （見出しにしたくない文字を表示するときは、上のフラグをONにする） 

//==================================================

// エフェクトをスキップするか否かのフラグ（システム変数）
if (sf.cskip === void)
  sf.cskip = true;  // 初回起動時にはfalseを代入しておく

// ［システム‐エフェクトスキップ］メニューハンドラの定義
kag.oncSkipClick = function(sender)
{
  sf.cskip = !sf.cskip;
  cSkipMenuItem.checked = sf.cskip;
} incontextof kag;

kag.menu.insert(kag.optionsMenu =
     new KAGMenuItem(this, "エフェクトスキップ(&G)", 0, kag.oncSkipClick, false), 2);
 kag.optionsMenu.stopRecur = true;

kag.optionsMenu.add(
     kag.cSkipMenuItem = new KAGMenuItem(
         this,
         "画面切り替えを行う(&T)",
         0,
         function(sender) { sf.cskip = sender.checked = !sf.cskip; },
         false));

if(sf.cskip === void) sf.cskip = true;
 kag.cSkipMenuItem.checked = sf.cskip;

//==================================================

// エフェクトをスキップするか否かのフラグ（システム変数）
if (sf.Asksave === void)
  sf.Asksave = false;  // 初回起動時にはfalseを代入しておく

// ［システム‐エフェクトスキップ］メニューハンドラの定義
kag.onAsksaveClick = function(sender)
{
  sf.Asksave = !sf.Asksave;
  AsksaveMenuItem.checked = sf.Asksave;
} incontextof kag;

kag.menu.insert(kag.optionsMenu =
     new KAGMenuItem(this, "確認ウィンドウ(&G)", 0, kag.onAsksaveClick, false), 2);
 kag.optionsMenu.stopRecur = true;

kag.optionsMenu.add(
     kag.AsksaveMenuItem = new KAGMenuItem(
         this,
         "画面切り替えを行う(&T)",
         0,
         function(sender) { sf.Asksave = sender.checked = !sf.Asksave; },
         false));

if(sf.Asksave === void) sf.Asksave = true;
 kag.AsksaveMenuItem.checked = sf.Asksave;

//==================================================

// ボイスをスキップするか否かのフラグ（システム変数）
if (sf.voice_cut === void)
  sf.voice_cut = false;  // 初回起動時にはfalseを代入しておく

// ［システム‐エフェクトスキップ］メニューハンドラの定義
kag.onvoice_cutClick = function(sender)
{
  sf.voice_cut = !sf.voice_cut;
  voice_cutMenuItem.checked = sf.voice_cut;
} incontextof kag;

kag.menu.insert(kag.optionsMenu =
     new KAGMenuItem(this, "ボイススキップ(&G)", 0, kag.onvoice_cutClick, false), 2);
 kag.optionsMenu.stopRecur = true;

kag.optionsMenu.add(
     kag.voice_cutMenuItem = new KAGMenuItem(
         this,
         "画面切り替えを行う(&T)",
         0,
         function(sender) { sf.voice_cut = sender.checked = !sf.voice_cut; },
         false));

if(sf.voice_cut === void) sf.voice_cut = true;
 kag.voice_cutMenuItem.checked = sf.voice_cut;

//==================================================

// 夜子ボイスをスキップするか否かのフラグ（システム変数）
if (sf.voice_01 === void)
  sf.voice_01 = false;  // 初回起動時にはfalseを代入しておく

// ［システム‐エフェクトスキップ］メニューハンドラの定義
kag.onvoice_01Click = function(sender)
{
  sf.voice_01 = !sf.voice_01;
  voice_cutMenuItem.checked = sf.voice_01;
} incontextof kag;

kag.menu.insert(kag.optionsMenu =
     new KAGMenuItem(this, "夜子オンオフ(&G)", 0, kag.onvoice_01Click, false), 2);
 kag.optionsMenu.stopRecur = true;

kag.optionsMenu.add(
     kag.voice_01MenuItem = new KAGMenuItem(
         this,
         "画面切り替えを行う(&T)",
         0,
         function(sender) { sf.voice_01 = sender.checked = !sf.voice_01; },
         false));

if(sf.voice_01 === void) sf.voice_01 = false;
 kag.voice_01MenuItem.checked = sf.voice_01;

//==================================================

// かなたボイスをスキップするか否かのフラグ（システム変数）
if (sf.voice_02 === void)
  sf.voice_02 = false;  // 初回起動時にはfalseを代入しておく

// ［システム‐エフェクトスキップ］メニューハンドラの定義
kag.onvoice_02Click = function(sender)
{
  sf.voice_02 = !sf.voice_02;
  voice_cutMenuItem.checked = sf.voice_02;
} incontextof kag;

kag.menu.insert(kag.optionsMenu =
     new KAGMenuItem(this, "かなたオンオフ(&G)", 0, kag.onvoice_02Click, false), 2);
 kag.optionsMenu.stopRecur = true;

kag.optionsMenu.add(
     kag.voice_02MenuItem = new KAGMenuItem(
         this,
         "画面切り替えを行う(&T)",
         0,
         function(sender) { sf.voice_02 = sender.checked = !sf.voice_02; },
         false));

if(sf.voice_02 === void) sf.voice_02 = true;
 kag.voice_02MenuItem.checked = sf.voice_02;

//==================================================

// 妃ボイスをスキップするか否かのフラグ（システム変数）
if (sf.voice_03 === void)
  sf.voice_03 = false;  // 初回起動時にはfalseを代入しておく

// ［システム‐エフェクトスキップ］メニューハンドラの定義
kag.onvoice_03Click = function(sender)
{
  sf.voice_03 = !sf.voice_03;
  voice_cutMenuItem.checked = sf.voice_03;
} incontextof kag;

kag.menu.insert(kag.optionsMenu =
     new KAGMenuItem(this, "妃オンオフ(&G)", 0, kag.onvoice_03Click, false), 2);
 kag.optionsMenu.stopRecur = true;

kag.optionsMenu.add(
     kag.voice_03MenuItem = new KAGMenuItem(
         this,
         "画面切り替えを行う(&T)",
         0,
         function(sender) { sf.voice_03 = sender.checked = !sf.voice_03; },
         false));

if(sf.voice_03 === void) sf.voice_03 = true;
 kag.voice_03MenuItem.checked = sf.voice_03;
//==================================================

// 理央ボイスをスキップするか否かのフラグ（システム変数）
if (sf.voice_04 === void)
  sf.voice_04 = false;  // 初回起動時にはfalseを代入しておく

// ［システム‐エフェクトスキップ］メニューハンドラの定義
kag.onvoice_04Click = function(sender)
{
  sf.voice_04 = !sf.voice_04;
  voice_cutMenuItem.checked = sf.voice_04;
} incontextof kag;

kag.menu.insert(kag.optionsMenu =
     new KAGMenuItem(this, "理央オンオフ(&G)", 0, kag.onvoice_04Click, false), 2);
 kag.optionsMenu.stopRecur = true;

kag.optionsMenu.add(
     kag.voice_04MenuItem = new KAGMenuItem(
         this,
         "画面切り替えを行う(&T)",
         0,
         function(sender) { sf.voice_04 = sender.checked = !sf.voice_04; },
         false));

if(sf.voice_04 === void) sf.voice_04 = true;
 kag.voice_04MenuItem.checked = sf.voice_04;
//==================================================

// 汀ボイスをスキップするか否かのフラグ（システム変数）
if (sf.voice_05 === void)
  sf.voice_05 = false;  // 初回起動時にはfalseを代入しておく

// ［システム‐エフェクトスキップ］メニューハンドラの定義
kag.onvoice_05Click = function(sender)
{
  sf.voice_05 = !sf.voice_05;
  voice_cutMenuItem.checked = sf.voice_05;
} incontextof kag;

kag.menu.insert(kag.optionsMenu =
     new KAGMenuItem(this, "汀オンオフ(&G)", 0, kag.onvoice_05Click, false), 2);
 kag.optionsMenu.stopRecur = true;

kag.optionsMenu.add(
     kag.voice_05MenuItem = new KAGMenuItem(
         this,
         "画面切り替えを行う(&T)",
         0,
         function(sender) { sf.voice_05 = sender.checked = !sf.voice_05; },
         false));

if(sf.voice_05 === void) sf.voice_05 = true;
 kag.voice_05MenuItem.checked = sf.voice_05;

//==================================================

// 闇子ボイスをスキップするか否かのフラグ（システム変数）
if (sf.voice_06 === void)
  sf.voice_06 = false;  // 初回起動時にはfalseを代入しておく

// ［システム‐エフェクトスキップ］メニューハンドラの定義
kag.onvoice_06Click = function(sender)
{
  sf.voice_06 = !sf.voice_06;
  voice_cutMenuItem.checked = sf.voice_06;
} incontextof kag;

kag.menu.insert(kag.optionsMenu =
     new KAGMenuItem(this, "闇子オンオフ(&G)", 0, kag.onvoice_06Click, false), 2);
 kag.optionsMenu.stopRecur = true;

kag.optionsMenu.add(
     kag.voice_06MenuItem = new KAGMenuItem(
         this,
         "画面切り替えを行う(&T)",
         0,
         function(sender) { sf.voice_06 = sender.checked = !sf.voice_06; },
         false));

if(sf.voice_06 === void) sf.voice_06 = true;
 kag.voice_06MenuItem.checked = sf.voice_06;
//==================================================

// 奏ボイスをスキップするか否かのフラグ（システム変数）
if (sf.voice_07 === void)
  sf.voice_07 = false;  // 初回起動時にはfalseを代入しておく

// ［システム‐エフェクトスキップ］メニューハンドラの定義
kag.onvoice_07Click = function(sender)
{
  sf.voice_07 = !sf.voice_07;
  voice_cutMenuItem.checked = sf.voice_07;
} incontextof kag;

kag.menu.insert(kag.optionsMenu =
     new KAGMenuItem(this, "奏オンオフ(&G)", 0, kag.onvoice_07Click, false), 2);
 kag.optionsMenu.stopRecur = true;

kag.optionsMenu.add(
     kag.voice_07MenuItem = new KAGMenuItem(
         this,
         "画面切り替えを行う(&T)",
         0,
         function(sender) { sf.voice_07 = sender.checked = !sf.voice_07; },
         false));

if(sf.voice_07 === void) sf.voice_07 = true;
 kag.voice_07MenuItem.checked = sf.voice_07;
//==================================================

// 岬ボイスをスキップするか否かのフラグ（システム変数）
if (sf.voice_08 === void)
  sf.voice_08 = false;  // 初回起動時にはfalseを代入しておく

// ［システム‐エフェクトスキップ］メニューハンドラの定義
kag.onvoice_08Click = function(sender)
{
  sf.voice_08 = !sf.voice_08;
  voice_cutMenuItem.checked = sf.voice_08;
} incontextof kag;

kag.menu.insert(kag.optionsMenu =
     new KAGMenuItem(this, "奏オンオフ(&G)", 0, kag.onvoice_08Click, false), 2);
 kag.optionsMenu.stopRecur = true;

kag.optionsMenu.add(
     kag.voice_08MenuItem = new KAGMenuItem(
         this,
         "画面切り替えを行う(&T)",
         0,
         function(sender) { sf.voice_08 = sender.checked = !sf.voice_08; },
         false));

if(sf.voice_08 === void) sf.voice_08 = true;
 kag.voice_08MenuItem.checked = sf.voice_08;
//==================================================

// クリソベリルボイスをスキップするか否かのフラグ（システム変数）
if (sf.voice_09 === void)
  sf.voice_09 = false;  // 初回起動時にはfalseを代入しておく

// ［システム‐エフェクトスキップ］メニューハンドラの定義
kag.onvoice_09Click = function(sender)
{
  sf.voice_09 = !sf.voice_09;
  voice_cutMenuItem.checked = sf.voice_09;
} incontextof kag;

kag.menu.insert(kag.optionsMenu =
     new KAGMenuItem(this, "クリソベリルオンオフ(&G)", 0, kag.onvoice_09Click, false), 2);
 kag.optionsMenu.stopRecur = true;

kag.optionsMenu.add(
     kag.voice_09MenuItem = new KAGMenuItem(
         this,
         "画面切り替えを行う(&T)",
         0,
         function(sender) { sf.voice_09 = sender.checked = !sf.voice_09; },
         false));

if(sf.voice_09 === void) sf.voice_09 = true;
 kag.voice_09MenuItem.checked = sf.voice_09;