//
// 履歴レイヤの各種パラメータを設定する
//
function MyHistoryLayer_config()
{

// ☆ここから…

;historyScrollLineNum = 5;		// 「前へ」「次へ」クリック１回あたりのスクロール行数

// 以下は縦書き用のパラメータ
;historyCloseButtonImageV = "bl_bt_closeV.png";		// 「閉じる」ボタンの画像ファイル名
;historyCloseButtonLeftV = 759;						// 同、Ｘ座標（ピクセル）
;historyCloseButtonTopV = 15;						// 同、Ｙ座標（ピクセル）
;historyPrevPageButtonImageV = "bl_bt_sprevV.png";	// 「前ページ」ボタンの画像ファイル名
;historyPrevPageButtonLeftV = 583;					// 同、Ｘ座標（ピクセル）
;historyPrevPageButtonTopV = 16;					// 同、Ｙ座標（ピクセル）
;historyPrevButtonImageV = "bl_bt_prevV.png";		// 「前へ」ボタンの画像ファイル名
;historyPrevButtonLeftV = 478;						// 同、Ｘ座標（ピクセル）
;historyPrevButtonTopV = 16;						// 同、Ｙ座標（ピクセル）
;historyNextButtonImageV = "bl_bt_nextV.png";		// 「次へ」ボタンの画像ファイル名
;historyNextButtonLeftV = 216;						// 同、Ｘ座標（ピクセル）
;historyNextButtonTopV = 16;						// 同、Ｙ座標（ピクセル）
;historyNextPageButtonImageV = "bl_bt_snextV.png";	// 「次ページ」ボタンの画像ファイル名
;historyNextPageButtonLeftV = 111;					// 同、Ｘ座標（ピクセル）
;historyNextPageButtonTopV = 16;					// 同、Ｙ座標（ピクセル）

// 以下は横書き用のパラメータ
;historyCloseButtonImageH = "bl_bt_closeH.png";		// 「閉じる」ボタンの画像ファイル名
;historyCloseButtonLeftH = 764;						// 同、Ｘ座標（ピクセル）
;historyCloseButtonTopH = 10;						// 同、Ｙ座標（ピクセル）
;historyPrevPageButtonImageH = "bl_bt_sprevH.png";	// 「前ページ」ボタンの画像ファイル名
;historyPrevPageButtonLeftH = 765;					// 同、Ｘ座標（ピクセル）
;historyPrevPageButtonTopH = 70;					// 同、Ｙ座標（ピクセル）
;historyPrevButtonImageH = "bl_bt_prevH.png";		// 「前へ」ボタンの画像ファイル名
;historyPrevButtonLeftH = 765;						// 同、Ｘ座標（ピクセル）
;historyPrevButtonTopH = 191;						// 同、Ｙ座標（ピクセル）
;historyNextButtonImageH = "bl_bt_nextH.png";		// 「次へ」ボタンの画像ファイル名
;historyNextButtonLeftH = 765;						// 同、Ｘ座標（ピクセル）
;historyNextButtonTopH = 332;						// 同、Ｙ座標（ピクセル）
;historyNextPageButtonImageH = "bl_bt_snextH.png";	// 「次ページ」ボタンの画像ファイル名
;historyNextPageButtonLeftH = 765;					// 同、Ｘ座標（ピクセル）
;historyNextPageButtonTopH = 424;					// 同、Ｙ座標（ピクセル）

// ☆ここまでの間のパラメータを修正してください

}

